lob/ui-components

.gitignore, README.md, babel.config.js, package-lock.json, package.json, src/assets/css/colors.css, src/components/Card/Card.vue, src/components/Card/index.js, src/components/index.js, src/main.js
Set up vue structure and set up repo to publish Vue components as a npm package.
=> Set up vue structure to publish Vue components

.npmrc, .storybook/preview.js, README.md, package-lock.json, package.json, src/config/icons.js, src/config/index.js, src/main.js
* Add and configure font awesome so we can use the icons throughout the project
* Created a `config` directory that we can use for future config. The pattern we'd like to use is create file that exports an object with a `configure` function. Then in `main.js` all the included config files will have configure called on them.
Getting the icons working was tricky but this [Github issue comment](storybookjs/storybook#12432 (comment)) saved the day
- `npm install` should work. Please let me know if it doesn't b/c I'm trying to figure out how to correctly handle FontAwesome auth without checking our token into the repo.
=> Add and configure font awesome

.circleci/config.yml, src/components/RadioButton/__tests__/RadioButton.spec.js
* [https://lobsters.atlassian.net/browse/DANG-180](https://lobsters.atlassian.net/browse/DANG-180)
* Add CircleCI checks for unit testing and linting whenever a commit is made
To test:
* Install CircleCI locally ([https://circleci.com/docs/2.0/local-cli/#installation](https://circleci.com/docs/2.0/local-cli/#installation))
* Configure CircleCI locally ([https://circleci.com/docs/2.0/local-cli/#configuring-the-cli](https://circleci.com/docs/2.0/local-cli/#configuring-the-cli))
* Run `circleci local execute --job build-test-lint`
Or, if you don't want to go through all of that, give me a shout and we can hop on a quick call so I can show you that it works.
=> DANG-180: Add CircleCI checks

src/assets/styles/main.scss, src/components/Card/Card.vue, src/components/RadioButton/RadioButton.vue, src/components/RadioGroup/RadioGroup.vue, src/theme/colors/Colors.vue, src/theme/fontSize/FontSize.vue, tailwind.config.js
* N/A
* Let's save our fingers and not type `tw-` everywhere because this is only going to be used in new projects
=> remove tw- prefix and use standard tailwind names

src/components/Checkbox/Checkbox.mdx, src/components/Checkbox/Checkbox.vue, src/components/Checkbox/__tests__/Checkbox.spec.js, src/components/RadioGroup/__tests__/RadioGroup.spec.js
* N/A
Now that we have folks consuming the components, I noticed some missing specs and added a little clarity to docs to help them going forward.
- things should still work and test suite should be green
=> Add missing specs and additional details to docs

src/components/Textarea/Textarea.mdx, src/components/Textarea/Textarea.stories.js, src/components/Textarea/Textarea.vue, src/components/Textarea/__tests__/Textarea.spec.js
* https://lobsters.atlassian.net/browse/DANG-125
* Create a textarea component for entering large blocks of text in a form.
=> textarea component for paragraphs of text

src/components/Checkbox/Checkbox.mdx, src/components/Checkbox/Checkbox.stories.js, src/components/MainNavigation/MainNavigation.mdx, src/components/MainNavigation/MainNavigation.stories.js
When a component has multiple stories, provide a descriptive name for each story.
If a component only has one story, we'll continue to use 'Primary' for the name.
=> DANG-186/story-names

src/components/TextInput/TextInput.vue
* [https://lobsters.atlassian.net/browse/DANG-114](https://lobsters.atlassian.net/browse/DANG-114)
* After dropping the text input into our new Dashboard, realized a few styling tweaks needed to be made for an optimal experience.
=> DANG-114, part 2: Styling tweaks to text input after dropping it in

package.json, src/components/MainNavigation/MainNavigation.vue
Put `<li></li>` around a list item.
=> Fix accessibility violation

src/components/MainNavigation/MainNavigation.vue, src/components/TopNavbar/TopNavbar.vue, src/components/index.js
* N/A
After using some of our components inside the app, had to make a few changes so that they style and work correctly.
=> Style cleanup

.stylelintrc, src/components/Table/Table.mdx, src/components/Table/Table.stories.js, src/components/Table/Table.vue, src/components/Table/TableBody.vue, src/components/Table/TableHeader.vue, src/components/Table/TableRow.vue, src/components/Table/__tests__/Table.spec.js, src/components/Table/__tests__/TableBody.spec.js, src/components/Table/__tests__/TableHead.spec.js, src/components/Table/__tests__/TableRow.spec.js
https://lobsters.atlassian.net/browse/DANG-136
Table component to display sets of data
=> DANG-136 Table component

package.json, src/assets/styles/main.scss, src/components/Checkbox/Checkbox.stories.js, src/components/Checkbox/Checkbox.vue, src/components/Table/Table.vue
* N/A
Our sign up page uses link in the checkbox label so I updated the logic to accept HTML. `v-html` can be a security risk but since the end-user isn't injecting HTML here and it's only for developers consuming the library, we're safe.
Also added some default link styling and cleaned up deprecation warnings while I was in there.
=> Html in checkbox labels

package.json, src/components/Typography/Typography.stories.js, src/components/Typography/Typography.vue
=> Add margins to text components.

package.json, src/components/Button/Button.mdx, src/components/Button/Button.vue, src/components/MainNavigation/MainNavigation.vue
* N/A (found while working on DANG-200)
* fix story name in Button.mdx
* flex button so stuff is centered if filling width
* more tweaks to main nav height styles
=> Moar cleanup

package.json, src/components/Button/Button.stories.js, src/components/Button/Button.vue
Adds the `success` and `error` variants for buttons.
=> Adds success&error button variants

package.json, src/components/Datepicker/Datepicker.vue, src/components/MainNavigation/MainNavigationChildItem.vue
* N/A
* Make sure datepicker isn't transparent
* Override default link styles for MainNav children (so they aren't blue)
=> fix some small style bugs

package.json, src/components/MegaMenu/MegaMenu.vue
Just adding some padding to megamenu titles for mobile views
=> Adds padding to better fit designs

package.json, src/components/MegaMenu/MegaMenu.stories.js, src/components/MegaMenu/MegaMenuSubtitle.vue
Creates a component for a mega menu subtitle (in the screenshot, "Docs & Resources"), with its particular text styling.
=> Creates megamenu subtitle component

package.json, src/components/MegaMenu/MegaMenu.stories.js, src/components/MegaMenu/MegaMenu.vue, src/components/MegaMenu/MegaMenuItem.vue
=> Fixes collapsed prop

package.json, src/components/MegaMenu/MegaMenu.vue, src/components/MegaMenu/MegaMenuItem.vue, src/components/MegaMenu/__tests__/MegaMenu.spec.js, src/components/TopNavbar/TopNavbar.vue
Changing the mega menu's breakpoint from MD to XL to match current top nav bar.
=> Changes megamenu breakpoint

package.json, src/components/MainNavigation/MainNavigation.vue, src/components/MainNavigation/MainNavigationItem.vue
=> Changes mainnav's breakpoint from md to xl, to match megamenu's and topNav's breakpoints

package.json, src/components/MainNavigation/MainNavigation.vue, src/components/MainNavigation/MainNavigationItem.vue
Forgot about the scss `md` to `xl` changes
=> Change mainnav breakpoint

package.json, src/components/index.js
Adds export for lobLink in index.js
=> Adds lobLink export

package-lock.json, package.json
=> update tailwind-plugin-lob to latest

package.json, src/components/Button/Button.stories.js, src/components/Button/Button.vue
* N/A
For some upcoming screens, (e.g. Mail Analytics) we have buttons that are styled as links and open filters upon click. This PR adds a link variant to our existing button component.
=> add link variant for button

package.json, src/components/Subnavigation/Subnavigation.mdx, src/components/Subnavigation/SubnavigationItem.vue, src/components/index.js
* N/A
Found some small things...
- add missing export for FilterContent
- Fix exact-active-class for Subnavigation 
- Clean up docs to use correct prop name
=> add missing export, fix exact-active-class, clean up docs

package.json, src/components/Datepicker/Datepicker.vue, src/components/FilterContent/FilterContent.vue
* N/A
Some more styling things for FilterContent and Datepicker.
The most interesting thing is sometimes we don't want the datepicker positioned absolute or hideable (those are true by default) but added props so we can toggle those off if we just need to use the datepicker like in the filters.
Also added the same logic to FilterContent as Datepicker that only allows one to be open at a time.
=> More housekeeping

package.json, src/components/Datepicker/__tests__/Datepicker.spec.js, src/components/SearchBar/SearchBar.stories.js, src/components/SearchBar/SearchBar.vue, src/components/SearchBar/__tests__/SearchBar.spec.js, src/components/TextInput/TextInput.vue, src/mixins/en.js
Fixed styling and small logic changes for SearchBar and TextInput
=> search and text input styling

package.json, src/components/SearchBar/SearchBar.vue
Change search results to be a slot
=> Search refactor

package-lock.json, package.json, src/components/FileUpload/FileUpload.vue
* [https://lobsters.atlassian.net/browse/DANG-280](https://lobsters.atlassian.net/browse/DANG-280)
* I dropped the `FileUpload` component in and realized it needed a couple of small tweaks.
=> DANG-280, pt2: FileUpload tweaks

package.json, src/components/Button/Button.stories.js, src/components/Button/Button.vue, src/components/Datepicker/DatepickerMonth.vue, src/components/Link/Link.vue, src/components/MainNavigation/MainNavigation.vue, src/components/MainNavigation/MainNavigationChildItem.vue, src/components/MainNavigation/MainNavigationItem.vue, src/components/MainNavigation/__tests__/MainNavigationChildItem.spec.js, src/components/MainNavigation/__tests__/MainNavigationItem.spec.js, src/mixins/translate.js
* Mostly N/A but also [DANG-281](https://lobsters.atlassian.net/browse/DANG-281)
* fix link button styling to match buttons (flex and center): when a LobLink had a button variant, text was left aligned. Fixed that so they'll look like our default buttons
* fix a11y bug in datepicker with incorrect label interpolation: I noticed some a11y errors when I was testing my screens ([this is one of the browser extensions I use](https://chrome.google.com/webstore/detail/wave-evaluation-tool/jbbplnpkjmmeebjpijfedlgcdilocofh)) 
* add none variant for button when we need a clickable element with no additional styling: the 'block' class resolves a browser bug where additional pixels are added to the button element but not on any of the normal box model places (padding, margin, border, etc)
* fix …
=> Mb more housekeeping

package.json, src/components/Datepicker/DatepickerMonth.vue
* N/A
* In Friday's EOW Frontend demo, it was pointed out that dates out of range should also be styled disabled. Fixed that.
=> disable date if its out of range of min and max

package-lock.json, package.json, src/components/RadioButton/RadioButton.mdx, src/components/RadioButton/RadioButton.vue
* N/A
* We have radio buttons with tooltips for further explanation, so need a slot to accommodate for that.
=> Add slot to radio button

package.json, src/components/FilterContent/FilterContent.stories.js, src/components/FilterContent/FilterContent.vue, src/components/MainNavigation/MainNavigation.vue, src/components/MegaMenu/__tests__/MegaMenu.spec.js, src/components/MegaMenu/__tests__/MegaMenuSubtitle.spec.js, src/components/Stepper/Stepper.vue, src/components/Stepper/__tests__/Stepper.spec.js, src/components/Tooltip/Tooltip.vue
* N/A (discovered while working on Advanced Filters)
* don't render tooltip if no content is provided (allow for conditional tooltips)
* remove default chevron from FilterContent (it shouldn't always be there)
* add additional test coverage and minor cleanup
=> Tweaks to tooltip and filter content

package.json, src/components/RadioButton/RadioButton.vue, src/components/RadioButton/__tests__/RadioButton.spec.js, src/components/RadioGroup/RadioGroup.stories.js, src/components/Tooltip/Tooltip.vue
* N/A (found while working on advanced filters)
* minor change: add z-index to tooltip
* 🚨 breaking change: add required id to radio button (using value as id meant that if there were multiple boolean radios on the page, Vue blew up) I'll try to add ids everywhere in a little PR in `dashboard-vue` so this doesn't catch us
* allow radio button to accept boolean value - we have places where we don't want to save strings but true/false
=> Radio accepts booleans

src/components/Button/Button.mdx, src/components/Button/Button.stories.js, src/components/Button/Button.vue
* https://lobsters.atlassian.net/browse/DANG-249
Add a yellow alert variant to LobButton
=> Adds 'alert' variant to LobButton.

package.json, src/components/SearchBar/SearchBar.vue
Changed width to full instead of max
=> Styling for search table

package.json, src/components/SearchBar/SearchBar.stories.js, src/components/SearchBar/SearchBar.vue
Documentation updated to reflect slots, computed prop for total results, no shadows on hover
=> Styling consistency and documentation fix

package-lock.json, package.json, src/components/Stepper/StepperItem.vue
* https://lobsters.atlassian.net/browse/DANG-283
* The checkbox was off-center which I fixed by playing around with padding/margin
BEFORE:
https://user-images.githubusercontent.com/85200846/127407799-f1515c1c-8470-48ab-a6d7-29717a987e94.png
AFTER: 
https://user-images.githubusercontent.com/85200846/127407706-c8742350-20bd-48ce-82b1-5a8cfeb0b0be.png
- first time using Git in production, did I do good??
- 🤞 
=> fixed checkbox spacing

.github/CODEOWNERS, package.json, src/components/Dropdown/Dropdown.vue, src/components/LobLabel/LobLabel.mdx, src/components/LobLabel/LobLabel.stories.js, src/components/LobLabel/LobLabel.vue, src/components/LobLabel/__tests__/LobLabel.spec.js, src/components/SearchBar/SearchBar.mdx, src/components/TextInput/TextInput.stories.js, src/components/TextInput/TextInput.vue, src/components/Textarea/Textarea.stories.js, src/components/Textarea/Textarea.vue, src/components/Textarea/__tests__/Textarea.spec.js
[Jira link](https://lobsters.atlassian.net/secure/RapidBoard.jspa?rapidView=106&projectKey=DANG&modal=detail&selectedIssue=DANG-282)
Refactor: Extracted `<label>`s into LobLabel component and replaced the labels in TextInput, Textarea, & Dropdown components.
No visible changes in the UI.
- may check that TextInput, Textarea, & Dropdown all work ok
- added myself to reviewers list
- added a lint-fix command to make it easier to fix red squigglies
=> DANG-282: LobLabel component

package.json, src/components/Dropdown/Dropdown.vue, src/components/Dropdown/DropdownItem.vue, src/components/Dropdown/DropdownItemGroup.vue
* https://lobsters.atlassian.net/browse/DANG-301
Fix unhandled error when clicking on dropdown placeholder or opt group name
=> DANG-301: Clicking placeholder in dropdown throws an error

package.json, src/components/Modal/Modal.mdx, src/components/Modal/Modal.stories.js, src/components/Modal/Modal.vue, src/components/Modal/__tests__/Modal.spec.js
* https://lobsters.atlassian.net/browse/DANG-299
* Since the `modelValue` prop in `Modal` was not a true `v-model`, we renamed it to `visible` so that it's not misleading
=> DANG-299: rename modelValue prop to visible

README.md, src/components/Button/Button.stories.js, src/components/FileUpload/FileUpload.stories.js, src/components/FilterContent/FilterContent.stories.js, src/components/Link/Link.stories.js, src/components/MegaMenu/MegaMenu.stories.js, src/components/RadioGroup/__tests__/RadioGroup.spec.js, src/components/SearchBar/SearchBar.mdx, src/components/SearchBar/SearchBar.stories.js, src/components/Table/Table.stories.js, src/components/TopNavbar/TopNavbar.stories.js, src/theme/fontSize/FontSize.stories.js
* N/A
* fix small typo in spec describe
* add note to README about this repo being public
* update search bar docs
* clean up story names in Storybook navigation (yay consistency)
=> Documentation updates

.github/CODEOWNERS
=> adding myself(sana) as codeowner

package.json, src/components/Button/Button.vue, src/components/Button/__tests__/Button.spec.js
* [A link to the JIRA ticket](https://lobsters.atlassian.net/secure/RapidBoard.jspa?rapidView=106&projectKey=DANG&modal=detail&selectedIssue=DANG-306)
* Button shows cursor-not-allowed when disabled
=> DANG-306: Button shows cursor-not-allowed when disabled

package.json, src/components/Link/Link.mdx, src/components/Link/Link.stories.js, src/components/Link/Link.vue, src/components/Link/__tests__/Link.spec.js
* Adds alert-button & underline property variants to LobLink
=> Adds alert-button variant to link.

package.json, src/components/SearchBar/SearchBar.mdx, src/components/SearchBar/SearchBar.stories.js, src/components/SearchBar/SearchBar.vue
Update props for header of search for more customizability and updated docs to reflect.
=> Refactor props + update docs

package.json, src/components/index.js
Exporting Stepper+StepperItem for use in Vue Dashboard
=> Stepper export

package.json, src/components/SearchBar/SearchBar.vue
=> Search Results Dropdown Typo

package-lock.json, package.json, src/components/Button/Button.mdx, src/components/DateInput/DateInput.mdx, src/components/DateInput/DateInput.stories.js, src/components/DateInput/DateInput.vue, src/components/DateInput/__tests__/DateInput.spec.js, src/components/Datepicker/Datepicker.mdx, src/components/FileUpload/FileUpload.mdx, src/components/FilterContent/FilterContent.mdx, src/components/Icons/Table.vue, src/components/Icons/index.js, src/components/Link/Link.mdx, src/components/LobLabel/LobLabel.mdx, src/components/LobLabel/LobLabel.stories.js, src/components/MegaMenu/MegaMenu.mdx, src/components/SearchBar/SearchBar.mdx, src/components/Switch/SwitchGroup.stories.js, src/components/Switch/SwitchItem.vue, src/components/Table/Table.mdx, src/components/TextInput/TextInput.stories.js, src/components/TextInput/TextInput.vue, src/components/TopNavbar/TopNavbar.mdx, src/components/index.js, src/mixins/en.js
* N/A
* rename Table icon to TableIcon to prevent collisions with html table element
* add slot and srOnlyLabel to SwitchItem to support rendering icons instead of text in some cases
* add DateInput to ui-components so other teams can use without copypasta
* fix storybook docs and story rendering issues
=> Date input and switch item refactor

package.json, src/components/Dropdown/Dropdown.vue
https://lobsters.atlassian.net/browse/DANG-318
I think Issue was that Dropbox was using a wrong class z-100 which doesn't really exist.. So switched that to z-50
=> DANG-318: Fix Dropbox z-index bug using un-existing class z-100.

package.json, src/components/TextInput/TextInput.stories.js, src/components/TextInput/TextInput.vue
* N/A
Support time type inputs.
=> add time type to text input

package.json, src/components/Breadcrumb/Breadcrumb.vue, src/components/Breadcrumb/__tests__/Breadcrumb.spec.js
* https://lobsters.atlassian.net/browse/DANG-316
* Always title case stuff in breadcrumb "Like This" not "Like this"
=> always title case breadcrumb text

package.json, src/components/DateInput/DateInput.stories.js, src/components/DateInput/DateInput.vue, src/components/Datepicker/Datepicker.vue, src/components/Datepicker/DatepickerDay.vue
* N/A
Sometimes we don't want a date in a date input.
=> allow date to be null in date inputs

package.json, src/components/Table/Table.stories.js, src/components/Table/TableHeader.vue, src/components/Table/TableRow.vue
* N/A
We need to be able to pass props/attributes to TableRow and TableHeader and have them actually work 🙃 
=> render table row and header with provided attrs

package.json, src/components/DateInput/DateInput.vue, src/components/Datepicker/Datepicker.vue
* N/A
* Sometimes we want a small date input 🤷 
=> pass size prop from date input to text input

package.json, src/components/LoadingIndicator/LoadingIndicator.mdx, src/components/LoadingIndicator/LoadingIndicator.stories.js, src/components/LoadingIndicator/LoadingIndicator.vue, src/components/LoadingIndicator/__tests__/LoadingIndicator.spec.js
* https://lobsters.atlassian.net/browse/DANG-344
* Partners team would like to use our loading indicator
=> add loading indicator

package.json, src/components/Dropdown/Dropdown.vue
=> set active option on updated in lifecycle too (not just created)

package.json, src/components/FileUpload/FileUpload.stories.js, src/components/FileUpload/FileUpload.vue
* N/A, found while working on signature logic
Allow dev to control size of file upload button and clear the input if needed.
=> File upload updates

package-lock.json, package.json, src/components/Badge/Badge.mdx, src/components/Badge/Badge.vue, src/components/Multiselect/Multiselect.mdx, src/components/Multiselect/Multiselect.stories.js, src/components/Multiselect/Multiselect.vue, src/components/Multiselect/__tests__/Multiselect.spec.js, src/components/TextInput/TextInput.mdx, src/components/TextInput/TextInput.vue, src/components/index.js, src/mixins/en.js, src/utils/array.js
* Parent ticket: [https://lobsters.atlassian.net/browse/DANG-383](https://lobsters.atlassian.net/browse/DANG-383)
* Specific subtask: [https://lobsters.atlassian.net/browse/DANG-426](https://lobsters.atlassian.net/browse/DANG-426)
* Creates a component that allows a user to filter a list of options based on what they type and select multiple options from the list.
* This half only contains mouse functionality, because I started working on keyboard navigability and it started getting very large so for the purposes of keeping manageable-sized PRs, here we are. [DANG-427](https://lobsters.atlassian.net/browse/DANG-427) will encompass the work for keyboard navigability and screen reader accessibility.
* You can pass in an array of strings or an array of objects. If passing in an array of …
=> DANG-426: Multiselect component, part 1 (mouse functionality)

package.json, src/components/Breadcrumb/Breadcrumb.vue, src/components/MainNavigation/MainNavigationChildItem.vue, src/components/MainNavigation/MainNavigationItem.vue
* N/A
- Don't underline main nav links
- Don't titleize breadcrumb display name so we can have full control
=> dont titleize breadcrumb display name and no underline main nav

package-lock.json, package.json, src/components/Modal/Modal.vue
* [https://lobsters.atlassian.net/browse/DANG-338](https://lobsters.atlassian.net/browse/DANG-338)
* When the modal content exceeds the height of the screen, the user is unable to scroll to see all of what's in the modal. 😢  This fixes that.
=> DANG-338: Make modal scrollable

package-lock.json, package.json, src/components/Modal/Modal.vue
* [https://lobsters.atlassian.net/browse/DANG-338](https://lobsters.atlassian.net/browse/DANG-338)
* Fixes the mistake I made in #160 where I forgot we actually have a lot of modals that don't need to take up most of the height 🙃 
* **Note: this will only be evident/work once [this PR](https://github.com/lob/tailwind-plugin-lob/pull/12) is merged into our tailwind config**
=> DANG-338: Make modal scrollable, part 2

package-lock.json, package.json, src/components/Dropdown/Dropdown.vue
[Jira link DANG 492](https://lobsters.atlassian.net/browse/DANG-492)
Reduces the vertical padding in Dropdown so that it will be the same size as the TextInput (in default size)
=> Dang 492/dropdown padding (tiny PR)

package.json, src/components/MegaMenu/MegaMenuItem.vue
[https://lobsters.atlassian.net/browse/DANG-307](https://lobsters.atlassian.net/browse/DANG-307)
Enter key was not working when clicking a submenu item in top nav - forgot to remove unnecessary code from previous pr.
=> fixed link not navigating to new page on enter

package.json, src/components/LobLabel/LobLabel.vue, src/components/RadioGroup/RadioGroup.vue, src/components/Switch/SwitchGroup.vue
Fixes scroll problems on partner API
tailwind .sr-only would not stay with other visual CSS classes
=> fix: sr-only should stay alone

package.json
no Jira ticket
This pr bumps up the version number because https://github.com/lob/ui-components/pull/178 has no version update
=> bump up the version

package-lock.json, package.json
Did not bump version number in previous merge
=> update version to .152

package.json, src/components/MainNavigation/MainNavigation.vue
[https://lobsters.atlassian.net/browse/DANG-752](https://lobsters.atlassian.net/browse/DANG-752)
This is a step towards fixing the empty space at the bottom of the main nav.  I need to main navigation component to emit an event when it is collapsed in order to be able to calculate what a sibling components relative distance from the left of the screen should be.
=> need main navigation to emit a collapsed event

package-lock.json
npm install after version bump to update package.json
=> version bump

package.json, src/components/MegaMenu/MegaMenuItem.vue
[JIRA ticket](https://lobsters.atlassian.net/browse/DANG-826)
adding `target` prop to `MegaMenuItem` so we can pass '_blank' where needed (authed top main nav Resources items)
=> dang-826 / add target prop to MegaMenuItem so we can pass blank where needed

package-lock.json, package.json, src/components/Subnavigation/Subnavigation.vue, src/components/Subnavigation/SubnavigationItem.vue
* [https://lobsters.atlassian.net/browse/DANG-455](https://lobsters.atlassian.net/browse/DANG-455)
* Subnavigation should not exceed screen width and should be scrollable.  
* Subnavigation items should not text wrap.
=> Dang 455/settings subnav responsiveness

package.json, src/components/SearchBar/SearchBar.vue
Part 1 of fix for https://lobsters.atlassian.net/browse/DANG-918
This closes the search bar when you click on an item within search results
=> close search on item click

package.json, src/components/index.js
I forgot to export the ProgressBar in the previous commit so it could not be imported to dashboard 🤦🏼‍♀️
=> export progressbar

package.json, src/components/Accordion/Accordion.mdx, src/components/Accordion/Accordion.vue, src/components/Accordion/__tests__/Accordion.spec.js
Added prop to accordion to allow for initial state to be passed in for accordion open/closed.
=> added accordion props

src/components/Link/Link.mdx, src/components/Link/__tests__/Link.spec.js
[JIRA ticket](https://lobsters.atlassian.net/browse/DANG-941)
adding this note to the LobLink doc in storybook
=> dang-941  Update LobLink docs to include that it will add noopener/noreferrer if target is blank

package-lock.json, package.json
* [A link to the JIRA ticket](https://lobsters.atlassian.net/browse/DANG-940)
* Allows people to work with repo with node versions that are more updated than the current one.
=> Node package versions to be >=14.16.1

src/components/Tooltip/Tooltip.vue
* [DANG-1030: Restyle tooltip component](https://lobsters.atlassian.net/browse/DANG-1030)
https://www.figma.com/file/h2T4pIQzH1M17LFGXMbJ4u/Design-System-(Blendr)-Hand-Off?node-id=138%3A1168
* Updates the color, padding, and text size to correspond with the design changes.
=> Change tooltip colors, etc

package.json, src/components/Dropdown/Dropdown.vue
* Updated dropdown item key to be unique
=> Key hotfix

package-lock.json, package.json, src/components/NewButton/NewButton.mdx, src/components/NewButton/NewButton.stories.js, src/components/NewButton/NewButton.vue, src/components/NewButton/__tests__/NewButton.spec.js
[dang-993 button primary styles](https://lobsters.atlassian.net/browse/DANG-993) & [dang-1024 button secondary styles](https://lobsters.atlassian.net/browse/DANG-1024)
**[Storybook NewButton](https://deploy-preview-234--elegant-yalow-f821c3.netlify.app/?path=/story/components-newbutton--default)**
**[figma for ref](https://www.figma.com/file/h2T4pIQzH1M17LFGXMbJ4u/Design-System-(Blendr)-Hand-Off?node-id=435%3A3587)**
✨ `NewButton` component will eventually replace `LobButton` (and can then be renamed to that), when design is finished and all states are added. 
More things to come - awaiting design:
- small size
- 'success' variant ??
Also adds the [recent changes to the TW plugin](https://github.com/lob/tailwind-plugin-lob/pull/18) that bring on the 'active' and 'focus' variants. …
=> dang-993-1024/NewButton

package.json, src/components/index.js
must export the new component!!
I always forget this bit 🤦🏼‍♀️ 😬
=> add the new component to exports - oops

src/components/MegaButton/MegaButton.mdx, src/components/MegaButton/MegaButton.stories.js, src/components/MegaButton/MegaButton.vue, src/components/MegaButton/__tests__/MegaButton.spec.js
* [DANG-1027 again](https://lobsters.atlassian.net/browse/DANG-1027)
Followup PR to megabuttons parts [1](https://github.com/lob/ui-components/pull/245), [2](https://github.com/lob/ui-components/pull/248), and [3](https://github.com/lob/ui-components/pull/249) integrating the feedback from [this convo](https://lob.slack.com/archives/C037J0X9PGD/p1652305353432839) with Adam.
As a bonus, this PR comes with a way to adjust params on the megabutton group story absolutely free!
=> Megabuttons design revisions

package-lock.json, package.json, src/components/MainNavigation/MainNavigationChildItem.vue, src/components/MainNavigation/MainNavigationItem.vue, src/components/NewLink/NewLink.vue
Adds the latest tw-plugin.
Fixes MainNavigation (child item) focus.
Wraps the new link in a `<span>` (inline) as the inline-block is not exactly right. A `<a>` is inline by default, & so is a span.
=> Update tw plugin & nit fix MainNavigation

package-lock.json, package.json
bump to publish the previous commit that fixes the navigation
=> version 1.0.0-beta.2

CHANGELOG.md
In order to make it easier for other teams/applications to follow what has changed in which version we now have a CHANGELOG!  Please make sure to add an entry following the convention established documenting the things that changed when you push a new version.
=> Added a Changelog

CHANGELOG.md, package-lock.json, package.json, src/components/NewButton/NewButton.vue, src/components/NewLink/NewLink.vue
to get a demo link for color primary-900 on hover - for NewLink & NewButton
=> fix: change hover to primary-900 for NewLink & NewButton styled as link (accessibility improvement)

CHANGELOG.md, package-lock.json, package.json, src/components/TextInput/TextInput.mdx, src/components/TextInput/TextInput.vue, src/components/TextInput/__tests__/TextInput.spec.js
* No ticket - relates to moving inputs into dashboard.  These are all the final changes that need to be made in order to update dashboard with the new inputs.
* There were issues with the login inputs, background needs to be set to white.
* Fixes to readonly state.
* Clear button is now optional, on a prop
=> last minute fixes to inputs

CHANGELOG.md, package-lock.json, package.json, src/components/MegaButton/MegaButton.stories.js, src/components/MegaButton/MegaButton.vue
The individual mega buttons had an external margin, which I remove.
=> Removes MegaButtons' right margin

CHANGELOG.md, package-lock.json, package.json, src/components/StepperVertical/StepperVertical.mdx, src/components/StepperVertical/StepperVertical.stories.js, src/components/StepperVertical/StepperVertical.vue, src/components/StepperVertical/StepperVerticalItem.vue, src/components/StepperVertical/__tests__/StepperVertical.spec.js, src/components/StepperVertical/__tests__/StepperVerticalItem.spec.js
[DANG-1271](https://lobsters.atlassian.net/browse/DANG-1271)
Updates `StepperVertical` to be used with campaigns on the dashboard.
=> DANG-1271 / update StepperVertical

CHANGELOG.md, package-lock.json, package.json, src/components/DateInput/__tests__/DateInput.spec.js, src/components/MegaButton/MegaButton.stories.js, src/components/MegaButton/MegaButton.vue
* [https://lobsters.atlassian.net/browse/DANG-1339](https://lobsters.atlassian.net/browse/DANG-1339)
* Megabuttons were too mega. This makes them a little less mega.
* Removed an extra div that wasn't doing anything useful.
* Story changes:
* Removed text from "With Image"
* Added "With Image and Small Text"
* Made some text shorter, since at 4 lines, we reach the max height set. [Asked in Slack](https://lob.slack.com/archives/C037J0X9PGD/p1656011611790209) what we should do about this.
=> DANG-1339/megabutton update (make them a little less mega)

src/components/StepperVertical/__tests__/StepperVertical.spec.js
so that there's no warning clogging the log 🙅🏼
=> add missing prop to steppervertical test 

CHANGELOG.md, package-lock.json, package.json, src/components/MegaButton/MegaButton.vue
* [https://lobsters.atlassian.net/browse/DANG-1339](https://lobsters.atlassian.net/browse/DANG-1339)
* Makes the max height of the image slightly larger, at the request of design.
=> DANG-1339/megabutton update pt2

CHANGELOG.md, package-lock.json, package.json, src/components/Dropdown/Dropdown.vue, src/components/RadioButton/RadioButton.vue, src/components/RadioButton/__tests__/RadioButton.spec.js, src/components/RadioButtonLarge/RadioButtonLarge.vue, src/components/RadioButtonLarge/__tests__/RadioButtonLarge.spec.js, src/components/RadioGroup/RadioGroup.stories.js, src/components/RadioGroup/RadioGroup.vue
* Design updates live with Tim and Shampa:
* Changed focus/checked and hover states of radio buttons
* Make chevron on dropdown darker
* Tim, Shampa, Myrtle and I discussed as a group and decided an error state on an individual radio button is not necessary.  If we want to show an error we would want it on the fieldset, not on an individual button.  Removed the error state classes, which makes the code much less verbose.
* Also removed the focus ring and box shadow from the dropdown
=> UI updates with product team

package-lock.json, package.json
https://lobsters.atlassian.net/browse/DANG-1410
CHANGELOGs:
vite: https://github.com/vitejs/vite/blob/v2.9.13/packages/vite/CHANGELOG.md
vitest: https://github.com/vitest-dev/vitest/releases
=> DANG-1410: Updated vite and vitest to latest

CHANGELOG.md, package-lock.json, package.json, src/components/Tooltip/Tooltip.vue
[* A link to the JIRA ticket
](https://lobsters.atlassian.net/browse/DANG-1471)
This is an update to the `ToolTip` component. It changes the `background-color` from `primary-700` to `gray-900`.
_**Before**_
_**After**_
=> Dang 1471/update tooltip component

CHANGELOG.md, package-lock.json, package.json, src/components/MegaButton/MegaButton.stories.js, src/components/MegaButton/MegaButton.vue
* Link to [FIGMA](https://www.figma.com/file/S2fDQOmDtOu3wGEYXk9o6x/Campaigns?node-id=3199%3A54642) designs calling for this style - see Custom Envelope button
=> DANG-1477 / add twoTone props and styles

amplify.yml
https://lobsters.atlassian.net/browse/DANG-1559
This adds the config file for the build settings to be used by Amplify
=> DANG-1559: Added build settings for Amplify

CHANGELOG.md, package-lock.json, package.json, src/components/Modal/Modal.vue
No Ticket
removed top padding on modal description if `noPadding` prop is `true`
=> removed top padding on modal description if nopadding prop is true

CHANGELOG.md, package-lock.json, package.json, src/components/MegaButton/MegaButton.vue
Add aria-disabled prop to MegaButton
=> add aria disabled prop

CHANGELOG.md, package-lock.json, package.json, src/components/RadioButtonLarge/RadioButtonLarge.stories.js, src/components/RadioButtonLarge/RadioButtonLarge.vue
In order to render these new radio buttons that take up half the available width, I'm adding a new `fullWidth` prop to radio buttons:
Also, fixes component's height, as it used to look wrong when the helper text used more than one line:
=> Dang-1701/step1 design updates: fix width and height for radio buttons

src/components/TextInput/TextInput.mdx, src/components/TextInput/TextInput.vue
https://lobsters.atlassian.net/browse/DANG-1584
As part of the analytics work for Signing Up we would like to be able to capture why a certain field was invalid and perform a custom function on that so this PR adds the native invalid handler.
https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/invalid_event
screenshot of the type of validationMessage we want access to
=> TextInput - add Invalid listener

CHANGELOG.md, package-lock.json, package.json
The version update and the changelog edits for my last PR https://github.com/lob/ui-components/pull/351
=> update version and edit changelog for last pr

CHANGELOG.md, package-lock.json, package.json, src/components/MainNavigation/MainNavigationChildItem.vue, src/components/MainNavigation/MainNavigationItem.vue
- updates the plugin to include the new gray color
- updates the Main Navigation color to gray-800
=> update to the new gray color

CHANGELOG.md, package-lock.json, package.json, src/components/SearchBar/SearchBar.vue
* [https://lobsters.atlassian.net/browse/DANG-1800](https://lobsters.atlassian.net/browse/DANG-1800)
Before:
After:
=> DANG-1800/remove background color from search bar when focused

CHANGELOG.md, package-lock.json, package.json
Trying to override 'latest' version number in npm with 2.0.0-beta.9
=> DANG-0000/update to beta.9

src/components/Pagination/PageArrowIcon.vue
rename the missed SkipToLeft/Right Icons to ChevronsLeft/Right
=> Dang-1746/fix: rename icons

CHANGELOG.md, package-lock.json, package.json, src/components/Table/Table.vue
* [https://lobsters.atlassian.net/browse/DANG-1828](https://lobsters.atlassian.net/browse/DANG-1828)
* Fixes overflowing tables
* I verified this fix using npm link
=> DANG-1828/fix overflowing tables

CHANGELOG.md, package-lock.json, package.json, src/components/Table/Table.vue
Remove the min width class I just added - not needed
=> DANG-1828/Table update: remove min-width class

CHANGELOG.md, package-lock.json, package.json, src/components/Dropdown/Dropdown.mdx, src/components/Dropdown/Dropdown.stories.js, src/components/Dropdown/Dropdown.vue, src/components/Dropdown/DropdownItem.vue, src/components/Dropdown/DropdownItemGroup.vue, src/components/Dropdown/__tests__/Dropdown.spec.js, src/components/Tooltip/Tooltip.vue
[DANG-1759](https://lobsters.atlassian.net/browse/DANG-1759) Dropdown component redesign
[zeplink](https://app.zeplin.io/project/6357fb022dba82821ad857bb/screen/63583c212b93ab33a2923d4e)
Visual redesign, no functional changes. 
I added a transition wrapper to the dropdown list so that it looks smoother.
There is a search functionality on the new designs which will be a followup ([DANG-1877](https://lobsters.atlassian.net/browse/DANG-1877) up for grabs if anyone is interested)
_I also updated the stories a little bit to make them more generic, less specialized._
please compare stories in demo link with the zeplin design, they should match
pending Michael's approval
[DANG-1759]: https://lobsters.atlassian.net/browse/DANG-1759?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJw …
=> Dang-1759/Dropdown component update

src/components/Subnavigation/Subnavigation.stories.js, src/components/Subnavigation/Subnavigation.vue, src/components/Subnavigation/SubnavigationItem.vue, src/components/Subnavigation/__tests__/SubnavigationItem.spec.js
[Dang-1853](https://lobsters.atlassian.net/browse/DANG-1853) Subnavigation update
[zeplink](https://app.zeplin.io/project/6357fb022dba82821ad857bb/screen/6387b4cdce4c198136db32cb)
- updates Subnavigation per new design (black theme)
- adds `disabled` prop to Item
_I must test locally on the dash make sure that I did not break anything._
=> Dang-1853/Subnavigation update

CHANGELOG.md, package-lock.json, package.json
Forgot to update the version and changelog in [this](https://github.com/lob/ui-components/pull/392) PR
=> DANG-1853/update version and changelog

CHANGELOG.md, package-lock.json, package.json, src/components/Checkbox/Checkbox.vue, src/components/Link/Link.vue, src/components/MegaButton/MegaButton.vue, src/components/RadioButton/RadioButton.vue, src/components/RadioButtonLarge/RadioButtonLarge.vue, src/components/Subnavigation/Subnavigation.vue, src/components/Switch/SwitchGroup.vue, src/components/TextInput/TextInput.vue, src/components/TopNavDropdown/TopNavButton.vue, src/components/TopNavDropdown/TopNavDropdown.vue, src/components/TopNavDropdown/TopNavDropdownItem.vue
Per [this](https://lob.slack.com/archives/C03E8L9DYMV/p1674054850904759) slack thread we are reducing the focus dashed outline widths to 1px
=> Dang-1921/reduce outline widths

CHANGELOG.md, package-lock.json, package.json, src/components/Dropdown/ConfirmChangeModal.vue, src/components/Dropdown/Dropdown.stories.js, src/components/Dropdown/Dropdown.vue, src/components/Dropdown/__tests__/ConfirmChangeModal.spec.js, src/components/Dropdown/__tests__/Dropdown.spec.js, src/mixins/en.js
This is along the same thing as what I did for the Dropzone.  I've added an optional confirm option change modal.
=> GC-152/confirm change on dropdown

CHANGELOG.md, package-lock.json, package.json, src/components/RadioButton/RadioButton.vue, src/components/RadioButtonLarge/RadioButtonLarge.vue
* [https://lobsters.atlassian.net/browse/GC-351](https://lobsters.atlassian.net/browse/GC-351)
* Click event was not being emitted from the container surrounding the large radio button
* This will fix the issue with progressive display in Dashboard campaigns UI
=> GC-351/add click emit

CHANGELOG.md, package.json, src/components/CurrencyInput/CurrencyInput.vue, src/components/CurrencyInput/currencyFormatter.js
*Previous PR failed to resolve the issue in dashboard-vue. These changes have been vetted against dashboard-vue's CI pipeline, and [seem to fix the issue](https://github.com/lob/dashboard-vue/actions/runs/5382783369). 
[BILL-3100]: https://lobsters.atlassian.net/browse/BILL-3100?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> BILL-3100 - Currency mount binding

CHANGELOG.md, package.json, src/components/TopNavDropdown/TopNavDropdown.stories.js, src/components/TopNavDropdown/TopNavDropdown.vue, src/components/TopNavDropdown/__tests__/TopNavDropdown.spec.js
* [GC-1326](https://lobsters.atlassian.net/browse/GC-1326)
* Updates the top nav dropdown component to support an icon variant.
[GC-1326]: https://lobsters.atlassian.net/browse/GC-1326?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> GC-1326 - Add Icon Variant for Top Nav

CHANGELOG.md, src/components/Label/Label.vue, src/components/Multiselect/__tests__/Multiselect.spec.js, src/components/TextInput/TextInput.vue
* Updates the input and label components with [new design system styles].(https://www.figma.com/file/DemxrOr7KWj78cfNVoUw7N/Vision-Design-System?type=design&node-id=316-3941&mode=design&t=Cga4bsOj7EtQOoiw-0).
[GC-1747]: https://lobsters.atlassian.net/browse/GC-1747?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> GC-1747/Input Updates

package.json
* Changelog was updated, but package version rev was missed in the last commit.
[GC-1747]: https://lobsters.atlassian.net/browse/GC-1747?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> GC-1747 Version wasn't revved in last update

README.md
* Adds a utility script example to the repo's readme.
[SELF-49]: https://lobsters.atlassian.net/browse/SELF-49?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SELF-49 Add icon script to readme

CHANGELOG.md, package-lock.json, package.json, src/components/MegaButton/MegaButton.vue, src/components/Modal/Modal.vue
[GC-1961](https://lobsters.atlassian.net/browse/GC-1961)
Accepts custom widths for mega buttons. This is needed in order to achieve [this modal.](https://www.figma.com/file/wcnyhGCMthUamrczESUzr3/Event-Based-Campaigns?type=design&node-id=2480-2764&mode=design&t=EQejAkhgLHGomQsT-0)
[GC-1961]: https://lobsters.atlassian.net/browse/GC-1961?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> GC-1961/restyles-megabuttons

CHANGELOG.md, package-lock.json, package.json, src/components/MegaButton/MegaButton.vue, src/components/Modal/Modal.vue
=> GC-1961/fixes megabuttons

CHANGELOG.md, package-lock.json, package.json, src/components/Icons/index.js
* [SELF-68](https://lobsters.atlassian.net/browse/SELF-68)
* Fixes the missing import of the `UserCircle` icon in icons `index.js`
[SELF-68]: https://lobsters.atlassian.net/browse/SELF-68?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SELF-68: Add `UserCircle` Icon

CHANGELOG.md, package-lock.json, package.json, src/components/Link/Link.vue
- [SELF-99](https://lobsters.atlassian.net/browse/SELF-99)
- Fixes the hover color for `upgrade-button` links
[SELF-99]: https://lobsters.atlassian.net/browse/SELF-99?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SELF-99: Fix Link `upgrade-button` Variant Hover Text Color

CHANGELOG.md, package-lock.json, package.json
- [SELF-135](https://lobsters.atlassian.net/browse/SELF-135)
- Forgot to update the package version in the previous PR
[SELF-135]: https://lobsters.atlassian.net/browse/SELF-135?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SELF-135: Update Package Version

CHANGELOG.md, package-lock.json, package.json, src/main.js
- [SELF-135](https://lobsters.atlassian.net/browse/SELF-135)
[SELF-135]: https://lobsters.atlassian.net/browse/SELF-135?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SELF-135: Fix `Icon` Component Registration

CHANGELOG.md, package-lock.json, package.json, src/components/NumberInput/NumberInput.vue
=> SELF-168: Fix Missing `maxFractionDigits`

CHANGELOG.md, package-lock.json, package.json, src/components/index.js
[- A link to the JIRA ticket](https://lobsters.atlassian.net/browse/GC-2490)
- Exporting the FloatingActionButton means people can now import the component, Mike.
=> GC-2490 export the FloatingActionButton

CHANGELOG.md, package-lock.json, package.json, src/components/Link/Link.vue, src/components/Link/__tests__/Link.spec.ts
- [SELF-189](https://github.com/lob/ui-components/pull/459)
- Before
- After
[SELF-189]: https://lobsters.atlassian.net/browse/SELF-189?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SELF-189: Fix Secondary Button Link Styles

CHANGELOG.md, package-lock.json, package.json, src/components/RadioButtonLarge/RadioButtonLarge.vue
- Adds a null ref guardrail for the radio input to fix a puzzling bug that's happening on the dash.
=> SELF-223/radio input bug

.gitignore, .storybook/preview.js, package-lock.json, package.json, setupTests.js, src/components/ImageFileUpload/ImageFileUpload.mdx, src/components/ImageFileUpload/ImageFileUpload.stories.ts, src/components/ImageFileUpload/ImageFileUpload.vue, src/components/ImageFileUpload/__tests__/ImageFileUpload.spec.ts, src/components/ImageFileUpload/__tests__/__snapshots__/ImageFileUpload.spec.ts.snap, src/components/ImageFileUpload/index.ts, src/globals.d.ts, src/main.ts, tailwind.config.js, vite.config.js
[MI-121](https://lobsters.atlassian.net/browse/MI-121)
[Figma](https://www.figma.com/file/qz0wJ4yY4RGPy1JqPqCIsM/Campaigns-v2?type=design&node-id=1691-10662&mode=design&t=XzEIzfC5fQUAostj-0)
- Adds an image upload component with drag and drop support
[MI-121]: https://lobsters.atlassian.net/browse/MI-121?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> MI-121: Add Image File Upload with Preview and Drag-n-Drop Support

CHANGELOG.md, package-lock.json, package.json
- Updates Vue version to match the dashboard
=> SELF-226/Update vue to 3.4

CHANGELOG.md, package-lock.json, package.json, src/main.ts, vite.config.js
- [SELF-238](https://lobsters.atlassian.net/browse/SELF-238)
- Fixes the PrimeVue dependency
[SELF-238]: https://lobsters.atlassian.net/browse/SELF-238?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SELF-238: Fix `PrimeVue` Vite Build

CHANGELOG.md, package-lock.json, package.json, src/components/DateInput/__tests__/DateInput.spec.ts, src/components/TextInput/TextInput.vue, src/components/TextInput/__tests__/TextInput.spec.ts, tsconfig.json
- [SELF-258](https://lobsters.atlassian.net/browse/SELF-258)
- Fixes a problem with the `TextInput` where it wasn't entirely clickable
[SELF-258]: https://lobsters.atlassian.net/browse/SELF-258?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SELF-258: Fix `TextInput` Clickbox

CHANGELOG.md, package-lock.json, package.json, src/components/TextInput/TextInput.vue
- SELF-258
- Quick follow up to fix the text styles for helper text
=> SELF-258: Fix Text Styles

CHANGELOG.md, package-lock.json, package.json, src/components/TextInput/TextInput.vue
=> SELF-258: Fix `TextInput` Ref

CHANGELOG.md, package-lock.json, package.json, src/components/DateInput/__tests__/DateInput.spec.js, src/components/TextInput/TextInput.vue, src/components/TextInput/__tests__/TextInput.spec.js, tsconfig.json
=> SELF-258: Revert `TextInput` Changes

CHANGELOG.md, package-lock.json, package.json, src/components/Steps/Steps.vue, src/components/TextInput/TextInput.vue
- [SELF-258](https://lobsters.atlassian.net/browse/SELF-258)
- Adds Steps hover state and fixes clickable box of text inputs
[SELF-258]: https://lobsters.atlassian.net/browse/SELF-258?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SELF-258: Add Steps Hover Styles

CHANGELOG.md, package-lock.json, package.json, src/components/Menu/Menu.vue, src/components/Overlay/Overlay.vue
- Turns out we have both `shadow-lg` and `shadow-large` classes 😭 
=> SELF-276/box shadow fix

.eslintrc, package-lock.json, package.json, src/components/Icons/Filter.vue, src/components/Icons/Map.vue, src/components/Textarea/Textarea.vue
- [SELF-284](https://lobsters.atlassian.net/browse/SELF-284)
- Upgrades ESLint for new Vue and Typescript feature support
[SELF-284]: https://lobsters.atlassian.net/browse/SELF-284?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SELF-284: Upgrade ESLint

CHANGELOG.md, package-lock.json, package.json, src/components/Menu/Menu.stories.ts, src/components/Menu/Menu.vue
- Add disabled styles for the menu items
[SELF-286]: https://lobsters.atlassian.net/browse/SELF-286?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SELF-286/disabled menu styles

CHANGELOG.md, package-lock.json, package.json, src/components/DataTable/DataTable.vue
=> SELF-253: Fix `DataTable` Errors

CHANGELOG.md, package-lock.json, package.json, src/components/DataTable/DataTable.vue
- [SELF-313](https://lobsters.atlassian.net/browse/SELF-313)
[SELF-313]: https://lobsters.atlassian.net/browse/SELF-313?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SELF-313: Refactor DataTable Borders

CHANGELOG.md, package-lock.json, package.json, src/components/Tile/Tile.mdx, src/components/Tile/Tile.stories.ts, src/components/Tile/Tile.vue, src/components/Tile/TileGroup.vue, src/components/Tile/__tests__/Tile.spec.ts, src/components/Tile/constants.ts, src/components/Tile/index.ts, src/utils/ConditionalLinkWrapper.vue
- [SELF-312](https://lobsters.atlassian.net/browse/SELF-312)
- Adds tile components
[SELF-312]: https://lobsters.atlassian.net/browse/SELF-312?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SELF-312: Add `Tile` Components

CHANGELOG.md, package-lock.json, package.json, src/main.ts
- [SELF-312](https://lobsters.atlassian.net/browse/SELF-312)
[SELF-312]: https://lobsters.atlassian.net/browse/SELF-312?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SELF-312: Export tiles

CHANGELOG.md, package-lock.json, package.json
[MI-257](https://lobsters.atlassian.net/browse/MI-257)
Missed bumping version and updating CHANGELOG in #503 
[MI-257]: https://lobsters.atlassian.net/browse/MI-257?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> MI-257: Version bump and update to CHANGELOG

CHANGELOG.md, package-lock.json, package.json, src/components/DataTable/DataTable.vue
- SELF-323
- Remove unnecessary datatable prop
- Align sort icon in header
=> SELF-323: DataTable Improvements

.eslintrc, src/components/Breadcrumb/Breadcrumb.vue, src/components/Calendar/Calendar.vue, src/components/ColorPicker/ColorPicker.vue, src/components/Datepicker/Datepicker.vue, src/components/Dropdown/Dropdown.vue, src/components/Dropdown/DropdownItemGroup.vue, src/components/LegacyModal/LegacyModal.vue, src/components/Pagination/PageArrowIcon.vue, src/components/Pagination/Pagination.vue, src/components/Stepper/StepperItem.vue, src/components/TextInput/TextInput.vue, src/components/Textarea/Textarea.vue
- Lint for Pascal component names
=> SELF-326: Pascal Component Lint Requirement

CHANGELOG.md, package-lock.json, package.json, src/assets/styles/main.scss, src/components/Grid/Grid.vue, src/components/Grid/GridItem.vue
- [SELF-290](https://lobsters.atlassian.net/browse/SELF-290)
- `Grid` loading state
- 
[SELF-290]: https://lobsters.atlassian.net/browse/SELF-290?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SELF-290: `Grid` Loading

CHANGELOG.md, package-lock.json, package.json, src/components/IconButton/IconButton.vue
- SELF-290
- Removes `onClick` required prop from `IconButton`
=> SELF-290: Fix `IconButton` `onClick` Prop Requirement

CHANGELOG.md, package-lock.json, package.json, src/assets/styles/main.scss, src/components/Panel/Panel.vue
- SELF-303
- Change panel click box
=> SELF-303: `Panel` Clickbox

CHANGELOG.md, package-lock.json, package.json, src/components/Modal/Modal.stories.js, src/components/Modal/Modal.vue
- SELF-303
- Adds margin to full screen modals
=> SELF-303: `Modal` Improvements

CHANGELOG.md, package-lock.json, package.json, src/components/Tile/Tile.stories.ts, src/components/Tile/Tile.vue, src/utils/isSlotEmpty.ts
- [SELF-363](https://lobsters.atlassian.net/browse/SELF-363)
- Skeleton updates within Tile component
[SELF-363]: https://lobsters.atlassian.net/browse/SELF-363?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SELF-363: `Skeleton` Updates

CHANGELOG.md, package-lock.json, package.json, src/components/Card/Card.vue, src/components/Tile/Tile.vue, src/utils/ConditionalClickWrapper.vue
- [SELF-346](https://lobsters.atlassian.net/browse/SELF-346)
- Fixes conditional clicking attribute handling
[SELF-346]: https://lobsters.atlassian.net/browse/SELF-346?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SELF-346: Fix Conditional Clicking Attributes

CHANGELOG.md, package-lock.json, package.json, src/components/Menu/Menu.stories.ts, src/components/Menu/Menu.vue, src/components/Menu/types.ts, src/utils/ConditionalWrapper.vue
- [SELF-325](https://lobsters.atlassian.net/browse/SELF-325)
- Improves `Menu` component by allowing passing of `class`es
[SELF-325]: https://lobsters.atlassian.net/browse/SELF-325?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SELF-325: Menu Improvements

CHANGELOG.md, package-lock.json, package.json
- [SELF-482](https://lobsters.atlassian.net/browse/SELF-482)
- Upgrade `vite` for security patches
[SELF-482]: https://lobsters.atlassian.net/browse/SELF-482?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SELF-482: Upgrade `vite`

CHANGELOG.md, package-lock.json, package.json
- [SELF-482](https://lobsters.atlassian.net/browse/SELF-482)
- Upgrade `jest-dom` for security patches
[SELF-482]: https://lobsters.atlassian.net/browse/SELF-482?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SELF-482: Upgrade `jest-dom`

CHANGELOG.md, package-lock.json, package.json, tsconfig.json
- [SELF-482](https://lobsters.atlassian.net/browse/SELF-482)
- Upgrades `storybook@7.6.17`
[SELF-482]: https://lobsters.atlassian.net/browse/SELF-482?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SELF-482: Upgrade `storybook@7.6.17`
