package-lock.json, package.json, src/components/Card/Card.mdx, src/components/RadioButton/RadioButton.mdx, src/components/RadioButton/RadioButton.stories.js, src/components/RadioButton/RadioButton.vue, src/components/RadioGroup/RadioGroup.mdx, src/components/RadioGroup/RadioGroup.stories.js, src/components/RadioGroup/RadioGroup.vue
* [https://lobsters.atlassian.net/browse/DANG-167](https://lobsters.atlassian.net/browse/DANG-167)
* Deleted extra line breaks from Card story documentation.
* Edited radio button/group components so that the `separate line` behavior (radio buttons stacked on top of one another instead of next to each other) is controlled via the radio group component, and not the individual buttons themselves.
* Added stories for radio button and radio group with documentation.
Radio Button component page
Radio Button documentation page
Radio Group component page
Radio Group documentation page
Video I made because STORYBOOK IS SO COOL
https://user-images.githubusercontent.com/20443660/118036090-5d94dc80-b329-11eb-818d-c0570948e5ba.mov
How to test:
* Pull down branch, `npm install` (if you haven't …
=> DANG-167: Add radio button component to Storybook

.storybook/main.js, package-lock.json, package.json, src/assets/styles/main.scss
* N/A
* resolve warning about add-on order when starting storybook
* Was receiving a warning in the Storybook console on startup that the `docs` addon should be declared before `essentials` so fixed that :)
* add Storybook accessibility addon
* The a11y is super nice for alerting devs to potential a11y concerns while we're developing new components. It was easy to add so I thought it'd be a nice little value-add. And here's [more documentation about the addon(https://github.com/storybookjs/storybook/tree/next/addons/a11y)
* add normalize.css to project
* [Normalize.css](http://nicolasgallagher.com/about-normalize-css/) resets some of the default browser CSS so that spacing, etc. is more standard and easier to deal with without overriding manually all over the place
- Here's what the a11y …
=> Configure a11y addon and normalize.css

.circleci/config.yml
* [https://lobsters.atlassian.net/browse/DANG-180](https://lobsters.atlassian.net/browse/DANG-180)
* Merged [FontAwesome PR](https://github.com/lob/ui-components/pull/11) and then forgot that we need to give FA a token and merged [CircleCI config](https://github.com/lob/ui-components/pull/14) and the build failed. 😬 
* Also changed the name of the workflow to be more representative of what it actually does.
Run `circleci local execute --job build-test-lint -e FONTAWESOME_NPM_AUTH_TOKEN=${TOKEN}` ([can't connect to UI environment variables](https://circleci.com/docs/2.0/local-cli/#limitations-of-running-jobs-locally))
=> DANG-180, pt 2: Add FontAwesome token & change workflow name

src/components/MainNavigation/MainNavigationChildItem.vue, src/components/MainNavigation/MainNavigationItem.vue, src/components/Switch/SwitchGroup.stories.js
* Main nav was updated for color contrast ratios. Also, we had a heavier font weight on `MainNavChildItem` but not on `MainNavItem`, so added that class to the latter too.
* Really small thing: it was bothering me that `SwitchGroup` was the only component in Storybook without a space between. 😬 
Before, unhovered state
After, unhovered state
Before, hovered state
After, hovered state
=> Update main nav contrast, format switch group name

src/components/Card/Card.vue, src/components/Checkbox/Checkbox.vue, src/components/RadioButton/RadioButton.vue, src/components/Switch/SwitchGroup.vue, src/components/Textarea/Textarea.vue, tailwind.config.js
Create reusable box-shadow config in tailwind.
Added `shadow` to use the default shadow that appears in most of the elements in Figma. And `shadow-input` and `shadow-input-selected` for radios and checkboxes.
There may still be some one-off shadows we need to define in scoped styles since they aren't used anywhere else in Figma (I'm looking at you buttons...)
=> DANG-192/reusable-shadows

src/components/TextInput/TextInput.stories.js, src/components/TextInput/TextInput.vue
Adds a `type` property to `TextInput` to support things like `date`, `password`, `email`, etc. since they are all kinds of text values.
=> Support additional text-like inputs

src/components/Dropdown/Dropdown.mdx, src/components/Dropdown/Dropdown.stories.js, src/components/Dropdown/Dropdown.vue
- Rename "large" to "default" in Dropdown
- Make that the default
=> Make Dropdown size consistent with TextInput

src/components/MegaMenu/MegaMenu.mdx, src/components/MegaMenu/MegaMenuItem.vue, src/components/TopNavbar/TopNavbar.stories.js, src/components/TopNavbar/TopNavbar.vue
- Make navigation header full-width (it was a bit shy before)
- Make icon for `MegaMenuItem`s optional (without affecting their spacing)
=> Header tweaks

package.json, src/components/Button/Button.stories.js, src/components/Button/Button.vue
- Using 'span' instead of 'button' fixes a problem where the custom 'button' component is used with its own appearance.
- Removes redundant focused outlines since there is already enough styling to know which option is selected.
=> Main navigation tweaks

src/components/Datepicker/Datepicker.mdx, src/components/Datepicker/Datepicker.stories.js, src/components/Datepicker/Datepicker.vue, src/components/Datepicker/__tests__/Datepicker.spec.js
* N/A
While working on the filter content component, I figured out a way to handle the document clicking (to close the component when clicking anywhere else) without using a bound component. So I went ahead and implemented that in the Datepicker too for consistency.
=> find way to handle document click without ref to bound element, stopPropagation instead

src/components/TextInput/TextInput.vue
While using the text input for the search bar, I realized focus was odd:
Replaced it with focus around the whole input, as per [the figma designs](https://www.figma.com/file/PFyulPE8zYVuRxRAhnhd7T/LOB-Design-System-(Updated)?node-id=30%3A282):
=> Fixes focus on text inputs

package.json, src/components/MegaMenu/MegaMenu.vue
Some megamenus are placed in the top right corner of the screen. For those, I added the right prop so they are visible.
=> Adds right prop to megamenu, for megamenus placed far right in the top navbar

package.json, src/components/Breadcrumb/Breadcrumb.stories.js, src/components/Breadcrumb/Breadcrumb.vue
* https://lobsters.atlassian.net/browse/DANG-224
When there is a nested route where the parent renders a `<router-view />` we were getting 2 matched route records returned by `this.$route.matched` which led to duplicate breadcrumb items. Made an update to grab the unique matched route records based on their paths, selecting the last record if there is more than one present (the last one will be the actual component which we want).
Before
After
=> DANG-224: fix breadcrumb showing duplicate item when nested route

package-lock.json, package.json, src/components/Datepicker/Datepicker.stories.js, src/components/Datepicker/Datepicker.vue
* https://lobsters.atlassian.net/browse/DANG-267
When more than 1 datepicker are present on the page, they all stayed open. We want only the most recently opened datepicker to be open.
We're using [mitt](https://github.com/developit/mitt), a tiny event bus package, to handle emitting global events. Mitt is the Vue 3 recommended library for event emitting since they removed the event emitter API from Vue 2.
Also added z-index since that was breaking for Marius on the Overview page.
=> Dang 267/datepicker bug

package-lock.json, package.json, src/components/Link/Link.vue
Hovering over a `primary-button` variant lobLink made the text disappear.
=> Fixes hover on primary button

package.json, src/components/Datepicker/Datepicker.vue, src/components/FilterContent/FilterContent.vue
* N/A
When datepickers are nested in filters, the click events on the window were firing in the wrong order. This caused the filters to be hidden if you clicked anywhere in the datepicker. We're now using `useCapture` to capture the events and dispatch them in the right order.
=> useCapture on window click events to correctly dispatch events for nested components

package.json, src/components/Dropdown/Dropdown.vue, src/utils/__tests__/object.test.js, src/utils/index.js, src/utils/object.js
* N/A
Javascript objects are passed by reference, duh. Need to check shallow equality rather than deep equality when checking for which obj the model value matches.
=> Shallow equality check when opts are objs

package-lock.json, package.json, src/components/RadioButton/RadioButton.vue
* N/A
* A few more radio button adjustments. Label needs to be `flex` so that it and the tooltip can go on the same line and aligned vertically without messing up other stuff. I thought the inner circle of the radio button was too large before and looked a bit wonky, so make it slightly smaller.
=> Small radio adjustments: Change label to flex, make inner circle smaller

package-lock.json, package.json, src/components/Button/Button.vue
The `primary`, `success`, and `error` variants were 2 pixels shorter than the `tertiary` and `secondary` variants, because they lacked borders. This PR fixes that.
=> Adds border to all buttons for consistent heights

package.json, src/components/MegaMenu/MegaMenu.vue
* [A link to the JIRA ticket](https://lobsters.atlassian.net/secure/RapidBoard.jspa?rapidView=106&projectKey=DANG&modal=detail&selectedIssue=DANG-308)
* Removes the extra bg from the outer div that showed as an extra non-rounded shadow behind the top-nav's (megamenu) dropdown.
This is really hard to see on StoryBook but visible on the dashboard. You could see the little pointy corners (not rounded) by changing storybook to darkmode - but the top shadow is hard to catch.
=> DANG 308: remove extra shadow from MegaMenu dropdown

package.json, src/components/TextInput/TextInput.vue
* Fixes the misbehaving copy-button.
**before:**
**after:**
=> fix copy button size in TextInput

package.json, src/components/FilterContent/FilterContent.mdx, src/components/FilterContent/FilterContent.stories.js, src/components/FilterContent/FilterContent.vue, src/components/FilterContent/__tests__/FilterContent.spec.js
* Found while working on [DANG-276](https://lobsters.atlassian.net/browse/DANG-276)
Add a `boundElement` prop to the FilterContent component. When present, if the click event triggered by clicking outside the FilterContent component was from clicking on the `boundElement` the event will not be propagated so that the `v-model:open` doesn't get mutated twice (once from FilterContent.hide() and the other from the bubbled up click event)
=> allow FilterContent to bubble event based on bound element

package-lock.json, package.json, src/components/RadioButton/RadioButton.mdx, src/components/RadioButton/RadioButton.vue
Absolute positioning on the input was causing the view to jump when a radio button was far enough down a page and was focused/clicked, so did the following:
* Removed absolute positioning
* Added/adjusted some small label styles
* Fixed psuedo element positioning
* Made label part of slot/the default to accommodate for optional tooltip icon positioning
* Removed `h-0`/`w-0` as that prevented default `required` tooltip from appearing
This is a bit hard to test because it requires a few specific conditions to be true, but happy to hop on a quick call and demo if you'd like.
=> Fix radio button focus/click causing view to jump

package-lock.json, package.json, src/components/DateInput/DateInput.vue
DateInput now accepts [Date, null] as modelValue, so that it can be null/empty/blank for using in the filters
the modelValue prop is required so in theory this won't affect any of the existing implementation
=> DateInput will also accept null so that it can be blank for filters

package.json, src/components/Stepper/Stepper.stories.js, src/components/Stepper/StepperItem.vue, src/components/Stepper/StepperItemBorder.vue
* N/A
If a stepper is not on a white background, we have to do some fancy CSS magic to set the background color for our half borders.
Before
After
=> fix borders on non-white background with backgroundColor prop

package.json, src/components/Subnavigation/Subnavigation.mdx, src/components/Subnavigation/Subnavigation.vue, src/components/Subnavigation/SubnavigationItem.vue
* N/A, discovered/needed while working on [DANG-431](https://lobsters.atlassian.net/browse/DANG-431)
* Gives `Subnavigation` an optional `ulClass` prop so that we can set `w-full` and `justify-between` to make the component expand/collapse to the full page width
* Replaces `router-link` in `SubnavigationItem` with `LobLink` component
* Makes `SubnavigationItem` look much closer to the designs
=> Add class prop to Subnav, SubnavItem improvements

.circleci/config.yml, package.json, src/components/Breadcrumb/Breadcrumb.mdx, src/components/Breadcrumb/Breadcrumb.stories.js, src/components/Breadcrumb/Breadcrumb.vue, src/components/Breadcrumb/__tests__/Breadcrumb.spec.js, src/components/Link/Link.stories.js, src/components/Link/Link.vue, src/components/Link/__tests__/Link.spec.js
* https://lobsters.atlassian.net/browse/DANG-429
This PR resolves the following bugs and desired behaviors.
- When viewing a specific resource, like `postcards/some-postcard-id`, if one clicks the breadcrumb link of it (like Postcards > Postcard), the route updates wrongly, and tries to redirect to something like `/postcards/:id`.
- We need to be able to translate the breadcrumb display text while keeping consistent route names
- Sometimes we may want to display dynamic breadcrumb text depending on the route params (e.g. resolve the id so we can display it in the breadcrumb)
- We want our LobLink to accept an object in case we want to use named routes and route params
=> Dang 429/breadcrumb bugs

package.json, src/components/MainNavigation/MainNavigation.stories.js, src/components/MainNavigation/MainNavigationChildItem.vue, src/components/MainNavigation/MainNavigationItem.vue, src/components/MainNavigation/__tests__/MainNavigationChildItem.spec.js
* https://lobsters.atlassian.net/browse/DANG-322
When the user was on a route like `/postcards/psc_ls094uwel98df`, the Postcards child nav item was not active. This PR fixes that bug and uses LobLinks instead of router-links (similar to the change Beth made in Subnavigation recently)
=> fix bug setting main nav child active for children routes

package.json, src/components/Switch/SwitchGroup.vue
* N/A
By adding `flex-wrap` to the div containing our switch items, we can control the width of the parent via a `class` prop and if it constrains the width, things will wrap nicely without overflowing. If we don't constrain the width, then it's all good and will look the same as normal.
Also added prop for conditionally choosing to center items.
=> Switch group style

package.json, src/components/Dropdown/Dropdown.stories.js, src/components/Dropdown/Dropdown.vue, src/components/LobLabel/LobLabel.stories.js, src/components/LobLabel/LobLabel.vue, src/components/TextInput/TextInput.stories.js, src/components/TextInput/TextInput.vue, src/components/Textarea/Textarea.stories.js, src/components/Textarea/Textarea.vue
[DANG-445
](https://lobsters.atlassian.net/browse/DANG-445)
The current implementation of tooltips involves an icon placed inside the input, which looks really cool and clean! But it's not great for accessibility and it doesn't work with the chevron for dropdowns. So for consistency and accessibility reasons, this PR moves the tooltip into LobLabel and updates three components that use tooltips and adds stories demonstrating their use:
* TextInput
* Textarea
* Dropdown
- We probably want to give some thought to how this works with keyboard only navigation.
- Are there any other components we should update prior to release?
=> Dang 445/tootlip icon in label

package.json, src/components/Modal/Modal.vue, src/components/Subnavigation/SubnavigationItem.vue
[https://lobsters.atlassian.net/browse/DANG-544](https://lobsters.atlassian.net/browse/DANG-544)
###Original ticket description:
Multiple times when creating new addresses the modal closed and I lost all my data and had to start again.
nav to postcard -> create new address
click anywhere within modal, move mouse outside of modal area, then release click
modal closes on mouseup, and you lose all your progress
expected:
modal only closes when you click outside of the modal.
This happens frequently since when selecting a field with the mouse if you don't release click while within the modal, it closes.
###My comments:
I noticed this is the behavior on all modals.  If you click inside the modal, drag the mouse, and release click outside of the modal, the modal will close.  Better behavior …
=> Dang 544 Modal close behavior 

package.json, src/components/MegaMenu/MegaMenu.vue, src/components/MegaMenu/MegaMenuItem.vue
[https://lobsters.atlassian.net/browse/DANG-307](https://lobsters.atlassian.net/browse/DANG-307)
You can now navigate the navbar with tab, enter to open submenu, esc to close submenu, and shift+tab to navigate backwards.
=> Top Nav focus rings

package.json, src/components/MegaMenu/MegaMenu.vue
[https://lobsters.atlassian.net/browse/DANG-307](https://lobsters.atlassian.net/browse/DANG-307)
This is another PR pertaining to DANG-307 Nav Focus Rings and Keyboard navigability. Previous PR has been merged already, but did not account for Megamenus containing two submenus. This fix allows submenus to close after tabbing out of last anchor tag in the submenu, it also closes the submenu if you shift + tab backwards out of the submenu. Hitting enter will navigate you to the selected link.
=> made improvements to topnav keyboard navigation

package.json, src/components/RadioButton/RadioButton.vue
[JIRA ticket](https://lobsters.atlassian.net/browse/DANG-739)
related PR: [https://github.com/lob/dashboard-vue/pull/341](https://github.com/lob/dashboard-vue/pull/341)
According to figma lob design the Checkbox and the RadioButton labels should look the same, normal size font and semibold. 
[https://www.figma.com/file/PFyulPE8zYVuRxRAhnhd7T/LOB-Design-System-(Updated)?node-id=31%3A453](https://www.figma.com/file/PFyulPE8zYVuRxRAhnhd7T/LOB-Design-System-(Updated)?node-id=31%3A453)
Before:
After:
Checkbox:
=> DANG-739 make RadioButton label look the same as the Checkbox label, as per lob figma design

package.json, src/components/RadioButton/RadioButton.vue
before _(because in the previous commit I changed the outer circle's top but not the dot's)_
after _(move dot to the center again)_
=> fix selected dot in radiobutton (missed in previous commit)

package-lock.json, package.json, src/components/Modal/Modal.vue
* [https://lobsters.atlassian.net/browse/DANG-690](https://lobsters.atlassian.net/browse/DANG-690)
- Tooltips are being cutoff by overflow-auto on create address modal - set overflow-x to visible, this automatically sets overflow-y to auto.
=> Dang 690/create address modal tooltips

package.json, src/components/RadioButton/RadioButton.stories.js, src/components/RadioButton/RadioButton.vue
[JIRA ticket](https://lobsters.atlassian.net/browse/DANG-776)
The [figma design](https://www.figma.com/file/PFyulPE8zYVuRxRAhnhd7T/LOB-Design-System-(Updated)?node-id=31%3A453) does not specify the styling in the case of the RadioButton being selected and disabled/readonly at the same time; so we've missed this and we are showing some blank disabled buttons in the dashboard Settings:
This changes the 'dot' class from hidden to a gray-ish color, so that the RadioButton will still show its value but the gray also indicates that it is disabled. Added a couple more cursor-not-allowed classes to disabled/readonly for better UX.
for ref, this is what they look like in the old dashboard:
=> when radiobutton disabled or readonly, show the value dot as grey

package.json, src/components/TextInput/TextInput.stories.js, src/components/TextInput/TextInput.vue, src/components/TextInput/__tests__/TextInput.spec.js
[JIRA ticket](https://lobsters.atlassian.net/browse/DANG-432)
Adding a 'Copied' Tooltip to show above the `TextInput` for 1.5 seconds when copying the text with the `withCopyButton` copy button.
These live in the `APIKeysModal` in the dashboard; on `/address-verification` click on 'Get your Api Keys' bottom right to pop the modal.
✨ [see the new story in the preview! ](https://deploy-preview-196--elegant-yalow-f821c3.netlify.app/?path=/story/components-text-input--with-copy-button) ✨ 
https://user-images.githubusercontent.com/50080618/147152786-b7fc006a-781e-4fc1-a23e-ff5309587abb.mov
old dashboard:
=> Dang 432/adds 'Copied' Tooltip to TextInput to show when copying with the Copy Button (withCopyButton prop)

package.json, src/components/TextInput/TextInput.vue
I missed a little thing in the previous PR. The absolute position of the div of the tooltip is relative to the outer TextInput div; and its height is much less when we have `srOnlyLabel` and the label is not there.
[preview link](https://deploy-preview-197--elegant-yalow-f821c3.netlify.app/?path=/story/components-text-input--with-copy-button&args=srOnlyLabel:true) `?path=/story/components-text-input--with-copy-button&args=srOnlyLabel:true`
before:
after:
=> fix the position of copied tooltip when srOnlyLabel

package-lock.json, package.json, src/components/Subnavigation/Subnavigation.vue
…pear on windows machines unless content overflows
* [https://lobsters.atlassian.net/browse/DANG-455](https://lobsters.atlassian.net/browse/DANG-455)
* This relates to a prior PR, which has already been merged [https://github.com/lob/ui-components/pull/198](https://github.com/lob/ui-components/pull/198).
* The problem: on Window's machines the x scrollbar was showing even when content was not overflowing, and this was ugly.
* The solution: changed overflow-x-scroll to overflow-x-auto so bar only shows when there is actually content to scroll.
=> Subnav responsiveness quickfix

package.json, src/components/Link/Link.vue
part 1 of [JIRA ticket](https://lobsters.atlassian.net/browse/DANG-837)
1. update the Link component to have a prop `target` with a default of `_self`
2. update the Link component to add the attribute `rel="noopener noreferrer"` when `target="_blank"`
=> dang-837/add to LobLink target prop (default _self) & rel noopener noreferrer when _blank

package-lock.json, package.json, src/components/Dropdown/Dropdown.mdx, src/components/Dropdown/Dropdown.vue, src/components/Modal/Modal.vue
* [https://lobsters.atlassian.net/browse/DANG-841](https://lobsters.atlassian.net/browse/DANG-841)
* Link to dashboard PR: [https://github.com/lob/dashboard-vue/pull/402](https://github.com/lob/dashboard-vue/pull/402)
* The problem: The modals/states were being 'cut off' due to not having the appropriate y overflow.  Scrolling was not possible.
* The fix: 1. Changed overflow-x-visible to overflow-y-auto 2. Added a listHeight prop to dropdown so height can be specified if necessary (such as on state dropdown) and dropdown will become scrollable.
This PR is the first part of changes that will also be submitted in Dashboard-Vue.
=> dang-841/dropdown and modal bug

package-lock.json, package.json, src/components/MainNavigation/MainNavigation.vue, src/components/MainNavigation/MainNavigationItem.vue
[https://lobsters.atlassian.net/browse/DANG-751](https://lobsters.atlassian.net/browse/DANG-751)
This is part 1 of a 2 part PR, the second PR will be in dashboard-vue.
[Link to PR in dashboard
](https://github.com/lob/dashboard-vue/pull/408)
The problem: 
* Currently, when the left navigation menu is collapsed and a user clicks either the Address Verification, Print & Mail, or API Logs icons, nothing happens.  
* This is because these are menu items with children, so they do not directly navigate the user anywhere.  
* In old Dashboard, when you click one of these options, the menu expands again with only the submenu for the item clicked expanded, showing all of the submenu items - For example, if you click the Print & Mail icon, the menu expands and ONlY the Print & Mail sub options will …
=> Dang 751/collapsed nav

package-lock.json, package.json, src/components/MainNavigation/MainNavigationItem.vue
[https://lobsters.atlassian.net/browse/DANG-751](https://lobsters.atlassian.net/browse/DANG-751)
Making refactor as suggested by peer review in dashboard PR [https://github.com/lob/dashboard-vue/pull/408](https://github.com/lob/dashboard-vue/pull/408)
$event.target.id does not need to be emitted, as id is already passed as a prop - cleaner to just emit this.id
=> Dang 751/collapsed nav refactor

package-lock.json, package.json, src/components/ProgressBar/ProgressBar.mdx, src/components/ProgressBar/ProgressBar.stories.js, src/components/ProgressBar/ProgressBar.vue, src/components/ProgressBar/__tests__/ProgressBar.spec.js
made for the FileUploader ([Jira link](https://lobsters.atlassian.net/browse/DANG-223)) ([figma](https://www.figma.com/file/hGGnuNxd58NEnAuGkwXckx/Lob-Dashboard---PMAPI---List-Loader?node-id=2589%3A17076))
**[Demo on Storybook](https://deploy-preview-204--elegant-yalow-f821c3.netlify.app/?path=/story/components-progressbar--indeterminate)** 
The bar can be indeterminate, or show the actual percentage if the number is passed in.
**Props:** percentage, by default 0/falsy
I made a custom bar and did not use the html `<progress/>` tag because it is really hard to style. It is probably doable but would take a lot of css & a lot of special selecting, it is not doable with TW.
**ARIA**
Aria tags info [here](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_ …
=> ProgressBar

package.json, src/components/Switch/SwitchGroup.vue, src/components/index.js
While working on the new List Loader feature, I wanted to utilize the Switch component in a form, side-by-side with the DateInput component. In doing so, I realized that the labels/legends don't really line up. This PR ensures that Switch's legend visually lines up with other form inputs. 
[Original PR/convo](https://github.com/lob/dashboard-vue/pull/449#discussion_r800981960)
Before:
After:
UI where it will be used!
=> Align SwitchGroup's legend with other form input labels

package-lock.json, package.json
[JIRA DANG-996  Update vue-cli libraries in dashboard-vue and ui-components](https://lobsters.atlassian.net/browse/DANG-996)
tried to update the `vue/cli-service version` to `5.0.3` , [it does not pass the build](https://app.circleci.com/pipelines/github/lob/ui-components?branch=dang-996%2Fupdate-vue-cli&filter=all) :(
also, the 5.0.3 version of the plugins has dependency conflicts with eslint & jest, and the babel one throws an error when serving the storybook
this updates them all to `4.5.16`, and everything works ok
=> DANG-996 update vue/cli to 4.5.16

src/utils/__tests__/array.test.js
Tests for ui-components were failing on main (check out [ui-components/actions](https://github.com/lob/ui-components/actions)), apparently since https://github.com/lob/ui-components/pull/211.
This is because the test itself was dependant on the underlying Node version. I explain: the error thrown by Node when trying to access a let's say `b` property of a null object changed from `Uncaught TypeError: Cannot read property 'b' of null` to `TypeError: Cannot read properties of null (reading 'b')`. You can try it yourself online with different Node versions [here](https://www.jdoodle.com/execute-nodejs-online/).
This PR removes the error's text, and just checks an error is thrown. *If you know of a more specific assessment to make, please tell*.
=> Fixes Array Test

package.json, src/components/Link/Link.mdx, src/components/Link/Link.stories.js, src/components/Link/Link.vue, src/components/Link/__tests__/Link.spec.js
As part of the List Loader project, I would like to be able to use the LobLink component for the Cancel & Back buttons pictured below, as they navigate the user to another path. But unlike LobButton, LobLink does not currently have a tertiary style. 
Additionally, I would like to be able to disable said Links as well, for example when a save is in progress, but there is no disabled style for LobLink. 
This PR adds a `tertiary-button` variant as well as a `disabled` prop. 
Tertiary button (with hover):
Tertiary button (disabled)
I copied the styles from the existing `LobButton` as much as possible.
I ran into a few issues with disabling... 
- `<anchor>` tags are not actually disable-able, unlike `<button>`s, so passing a `disabled` attribute didn't do anything. I had to instead use CSS …
=> Add `tertiary` and `disabled` props to LobLink

package.json, src/components/Switch/SwitchGroup.stories.js, src/components/Switch/SwitchItem.vue
* N/A, but needed for [DANG-1036](https://lobsters.atlassian.net/browse/DANG-1036)
* We'd like to disable the "Set Target Delivery Date" SwitchItem in the campaigns workflow for now, since we'll be launching the beta without it. _However_, as our SwitchItem stands now, the only thing that this means is that when you click on the disabled choice, ... nothing happens.
* This adds our disabled background color that we use elsewhere (e.g. buttons) + a cursor-not-allowed class to make it clear that you can't click on it.
(unfortunately this screenshot doesn't show the 🚫  cursor, but we have Netlify previews for that)
* heh, so we have a test that checks that the input itself is disabled. I spent a few minutes trying to pull the label specifically to check that `cursor-not-allowed` was added, …
=> add CSS to SwitchItem disabled state to make it more clear to the user

package.json, src/components/Tooltip/Tooltip.vue
[dang-1058 glitchy tooltip icon in US Verifications view](https://lobsters.atlassian.net/browse/DANG-1058) 
The tooltip seems to glitch terribly when sitting in flex with justify-between. I cannot explain why exactly this only happens in justify between 🤨 
But it seems to be an issue with 'hidden' (which is TW for display:none = removing element from the DOM)
I tried auto margins, fixed height, other things - on the dashboard side - but none seems to work.
The outer div of the tooltip content is using the hidden property but it does not need it, as the content div uses opacity to hide/show the content. Removing this fixes the problem with the flex display.
**Demos:
with hidden**
https://user-images.githubusercontent.com/50080618/160868574-9bffe30a-ad9a-4fee-b034-57efecaccee4.mov
**without …
=> dang-1058/fix: remove display:none from tooltip content container to fix glitch

package.json, src/components/Switch/SwitchItem.vue
[DANG-1031 Restyle of Switch component](https://lobsters.atlassian.net/browse/DANG-1031)
[figma](https://www.figma.com/file/h2T4pIQzH1M17LFGXMbJ4u/Design-System-(Blendr)-Hand-Off?node-id=139%3A1399)
Restyle the Switch as per figma: 
- SwitchItem changes: slightly less px/width, less rounded corners, default font thin & blue, active item font semi-bold, 
- SwitchGroup gets a new shadow ✨ 
default `shadow` [changed in TW plugin](https://github.com/lob/tailwind-plugin-lob/pull/15)
**old:**
**new:**
=> Dang 1031/Restyle of Switch component

package.json, src/components/Tooltip/Tooltip.vue
this should fix the tooltip issues in [dang-1081](https://lobsters.atlassian.net/browse/DANG-1081) and [dang-1084](https://lobsters.atlassian.net/browse/DANG-1084)
reverting #218 (that broke them tooltips ^) so I will look at [dang-1058](https://lobsters.atlassian.net/browse/DANG-1058) again and find another way to fix the glitch
Putting the 'hidden' back in the Tooltip because I was wrong and 'hidden' is actually much required. 🤦🏼‍♀️
=> Tooltip should be hidden when not hovered (revert #218)

package-lock.json, package.json, vite.config.js
The latest updates to use vite to build this package required additional configuration in order to prevent Vue from being bundled in the package.  Trying to update Dashboard to use the latest version 0.0.179 is breaking Dashboard.  This should remove the bundling of Vue in the package.
=> Fix package breaking in version 0.0.179

package-lock.json, package.json
When trying to import the latest version of this library after switching to building with vite we get an error on line:
```
import '@lob/ui-components/dist/ui-components.css';
```
Stating
> Missing "./dist/ui-components.css" export in "@lob/ui-components" package
Even changing to import `style.css` doesn't fix it because we haven't specified that the `css` file be exported in the package.  This adds the file to the included exports.
=> Fix css export

package.json, src/components/NewButton/NewButton.mdx, src/components/NewButton/NewButton.stories.js, src/components/NewButton/NewButton.vue
Some styling changes following [discussion on Slack](https://lob.slack.com/archives/C037J0X9PGD/p1650485832640789).
- fixed height (regular: 48px, small: 32px)
- letter-spacing -0.04em
- change focus ring to be visible only for keyboard navigation/tabbing
- add `small` prop for small size button (text 14px)
**regular / small**
=> newbutton updates: fixed height, letter-spacing, focus-visible, small size

package.json, src/components/Alert/Alert.mdx, src/components/Alert/Alert.stories.js, src/components/Alert/Alert.vue
fix for a couple things we didn't catch: 
- the Alert div should have items-center class.
- the icon needs a no-shrink because it sits in flex.
- the text & link need a block wrapper so that the link can sit as inline-flex.
**before:**
**after:**
=> Fix alert style nits

package-lock.json, package.json, src/components/Alert/Alert.vue, src/components/Icons/Checkmark.vue, src/components/Icons/Error.vue, src/components/Icons/Info.vue, src/components/Icons/Warning.vue
see [Alerts figma here](https://www.figma.com/file/h2T4pIQzH1M17LFGXMbJ4u/Design-System-(Blendr)-Hand-Off?node-id=145%3A1288)
The Icons: Checkmark Warning Info and Error have slightly changed.
Copying the svg from figma gives you the fixed color that is in use in that design. But we use Icons with other colors too so we should be allowing the svg to read currentColor instead of a fixed color. (passed in as ie. text-{color})
This commit puts currentColor on the stroke of these svgs.
To confirm it works look at the Alert icons and compare with the Info icon used in the tooltip of textinput in storybook.
=> fix: give Icons currentColor instead of fixed color

package-lock.json, package.json, src/components/Alert/Alert.vue, src/components/Switch/SwitchItem.vue
- The text should be regular and not light. (we should also be able to have bold text in it as well)
- The padding above and below the text/icon block should be 12.
- The right / left to the dark line padding on the light background box should be 16, think it is 18.
requested changes implemented, new screenshots:
**[Alert review thread on Slack](https://lob.slack.com/archives/C037J0X9PGD/p1651066123161959)** for ref
=> final nits on Alert, font and padding changes as advised by Adam

package-lock.json, package.json, src/components/NewLink/NewLink.vue
Setting `inheritAttrs` to false at component level this will stop the role="link" and data-testIds etc from duplicating in tests
we are using v-bind to pass the attrs onto the inner element which is the actual link
**[Vue docs on disabling attribute inheritance](https://vuejs.org/guide/components/attrs.html#disabling-attribute-inheritance)**
=> NewLink nit: set inheritAttrs to false at component level this will stop attrs duplicating

package-lock.json, package.json, src/components/NewLink/NewLink.vue, src/components/Subnavigation/SubnavigationItem.vue, src/components/Subnavigation/__tests__/SubnavigationItem.spec.js
One more little nit on the NewLink. I noticed the [Alert got wonky](https://ui-components.lob.com/?path=/story/components-alert--primary) because the link was a block. 
This makes the NewLink wrapper to be `inline-block` so that it sits nicely inside text.
[see Alert in preview](https://deploy-preview-257--elegant-yalow-f821c3.netlify.app/?path=/story/components-alert--primary)
[see NewLink in preview](https://deploy-preview-257--elegant-yalow-f821c3.netlify.app/?path=/story/components-newlink--regular-link)
adds fix for Subnavigation that was broken because of NewLink attr inheritance
=> fix: change newlink wrapper to be inline-block so it sits better in text

CHANGELOG.md, package-lock.json, package.json, src/components/FileUpload/FileUpload.stories.js, src/components/FileUpload/FileUpload.vue
[dang-1254](https://lobsters.atlassian.net/browse/DANG-1254)
we'd missed this because it is not a button but an input component styled as one
changes:
- new button style, secondary only
- prop 'size' is now 'small' as we only use regular and small (no large is in use, and there is not a large new button style)
on the dashboard it looks like this:
=> Dang 1254/upload file with new secondary button style

src/theme/colors/Colors.vue
current Colors is [a little bit broken ](https://ui-components.lob.com/?path=/story/theme-dev-only-colors--primary)
it is because we put the colors back into theme and out of extend
this fixes it
=> fix colors story as we put them back in theme

package-lock.json, package.json, src/components/Dropdown/Dropdown.vue, src/components/Dropdown/DropdownItem.vue
*[https://www.figma.com/file/h2T4pIQzH1M17LFGXMbJ4u/Design-System-(Blendr)-Hand-Off?node-id=994%3A9675]( https://www.figma.com/file/h2T4pIQzH1M17LFGXMbJ4u/Design-System-(Blendr)-Hand-Off?node-id=994%3A9675)
* Small dropdowns should be 32 px - this was not in the original dropdown design, but showed up on the text input design.  I also updated the height of dropdown item - It should be 40px - for default - small variant was not specified so I picked 28px.  Also made contents of dropdown align center via flex positioning so we could get rid of some of the absolute positioning.
=> Update dropdown size

CHANGELOG.md, package-lock.json, package.json, src/components/Dropdown/Dropdown.vue, src/components/Dropdown/DropdownItem.vue, src/components/TextInput/TextInput.vue
While moving text inputs into dashboard I discovered that the clear button on the text inputs was causing form submissions in the dashboard.  Not entirely sure why, but preventing default on the button fixes the issue.  Since I was making updates I went ahead and made some typography changes to small dropdown variant.  The original dropdown designs did not include specs for small variant, and needed changes were not noticed until working on text inputs.
* Explains generally what the ticket is and why we are doing it
=> fixes for input components

CHANGELOG.md, package-lock.json, package.json, src/components/Textarea/Textarea.stories.js, src/components/Textarea/Textarea.vue
* ~~N/A, found while working on reskin of campaigns name modal~~ ok I created a ticket for it, [https://lobsters.atlassian.net/browse/DANG-1276](https://lobsters.atlassian.net/browse/DANG-1276)
* Previously, you had to pass through an `inputClass` to make the width something else. To be consistent with the rest of many of our other components, added a `w-full` class.
* Also, we were setting the height via a style block, and that seems ... unnecessary. (Also causing issues when trying to override it.)
* Also changed the rounded corner radius and focus/"has something in it" states to match the text input, since they're now on top of one another in the campaigns name modal and it's very obvious that they were different. 😬 
Before:
After:
=> DANG-1276/Update Textarea styles to match TextInput

CHANGELOG.md, package-lock.json, package.json, src/components/NewButton/NewButton.vue, src/components/NewLink/NewLink.vue, src/components/NewLink/__tests__/NewLink.spec.js
The warning button should still be dark red, so 'coral-900'. (not 'error')
=> Fix buttons warning colors - new branch to fix the preview

CHANGELOG.md, package-lock.json, package.json, src/components/Icons/ToolTip.vue
to avoid the clash with the Tooltip component
=> fix: change the export name of the ToolTip icon to ToolTipIcon

CHANGELOG.md, package-lock.json, package.json, src/components/Dropdown/Dropdown.vue, src/components/Dropdown/__tests__/Dropdown.spec.js
https://lobsters.atlassian.net/browse/DANG-1280
For a dropdown if you hover on an option and then click outside of the dropdown to close it without selecting an option, it selects the option that was last hovered when your cursor was still over the dropdown drawer
This was because the `onBlur` event was firing and calling `selectOption`. 
So i've removed that call to `selectOption`.
https://www.loom.com/share/3cd6770cece94213acf87cdb9ac547eb
- In the drowdown component -> open the dropdown drawer (is this the correct term?) -> move the mouse over any option -> click somewhere else on the screen to close the dropdown => the dropdown option should still show the placeholder value.
- In the drowdown component -> open the dropdown drawer -> select an option -> open the dropdown drawer again …
=> DANG-1280: dropdown hover/selector bug

package-lock.json, package.json, src/components/MegaButton/MegaButton.vue
https://lobsters.atlassian.net/browse/DANG-1289
Fixes the megabuttons text color from ` text-gray-700` to `text-gray-900`
Before:
After:
=> DANG-1289 fix megabutton text color

CHANGELOG.md, package-lock.json, package.json, src/components/NewLink/NewLink.vue
tiny nit and not reproducible on storybook
the text on a `NewLink variant="secondary-button"` turns blue on hover when it is pointing to an internal route. Hopefully this fixes it.
=> fix: maintain text-gray-500 on hover for NewLink secondary-button variant

CHANGELOG.md, package-lock.json, package.json, src/components/NewLink/NewLink.vue
Removes the blue bg-color (remnant) and the `:not(:active)` variant from the styleblocks, so that the bg gradient stays the same across default/hover/active etc. 
The NewButton had the correct combo but the NewLink didn't.
=> fix: active background color in newlink (button style)

CHANGELOG.md, package-lock.json, package.json, src/components/LobLabel/LobLabel.vue, src/components/TextInput/TextInput.vue, src/components/Textarea/Textarea.vue
Changes as advised by Tim/Shampa during design live session.
**[figma ref](https://www.figma.com/file/jJIuBK6U2i50x4v7c9jbrF/Lob-Design-System-2.0?node-id=931%3A6538)**
- removes the shadow on hover
- focus shows a gray-300 border instead
- input with value but unfocused maintains the gray-100 border
- the error state text color is the default
- removes the disabled prop from LobLabel - the label will stay the same color when TextInput is disabled
will add the changelog & package changes when it is time to merge :)
=> updates TextInput hover & focus style 

CHANGELOG.md, package-lock.json, package.json, src/components/RadioButton/RadioButton.vue, src/components/RadioButtonLarge/RadioButtonLarge.vue, src/components/RadioGroup/RadioGroup.vue
* [https://lobsters.atlassian.net/browse/DANG-1341](https://lobsters.atlassian.net/browse/DANG-1341)
* This should fix the margin issues we are seeing in dashboard for radio buttons
When I bring this into the dashboard I will move the large prop from the radio groups as it should no longer be needed
=> DANG-1341/radio button margin fixes

package-lock.json, package.json, src/theme/colors/Colors.vue, tailwind.config.js
ui-components stories for FontSize, Color, & Typography need fixing/updating - This PR is for Colors only
[DANG-1393](https://lobsters.atlassian.net/browse/DANG-1393)
- includes this change: [removed all tertiary colors from the config](https://github.com/lob/tailwind-plugin-lob/pull/37).
- removes transparent & current from the Story
- whitelists all colors
- changed to h2 because it looks better to me but open to all ideas :)))
=> DANG-1393 / fix the Colors story so that all colors display

CHANGELOG.md, package-lock.json, package.json, src/components/Accordion/Accordion.vue
[DANG-975 Accordion > header color doesn't have sufficient contrast](https://lobsters.atlassian.net/browse/DANG-975)
- changed text & icon color from primary-300 to 500
**before // after :**
=> Dang 975/accordion color

CHANGELOG.md, package.json, src/components/MainNavigation/MainNavigationChildItem.vue
[DANG-756](https://lobsters.atlassian.net/browse/DANG-756)
In the dashboard, there were (at least) 3 cases in which a `MainNavigationChildItem` would incorrectly render with an active state, although we were not visiting its page:
1. When visiting `/settings/logs`, navigation item `API Logs (/logs)` would get the active state too
2. When visiting `/settings/editions/us-verifications`, `US Verifications (/us-verifications)` would get the active state too
3. When visiting `/settings/editions/intl-verifications`, `Int'l Verifications (/intl-verifications)` would get the active state too
Case 1:
Case 2:
I changed the active state to only be true when the `to` prop **starts with** the current route, instead of just includes it. You can see in the examples above how the previous behavior was …
=> DANG-756/active-route-bug-fix

CHANGELOG.md, package-lock.json, package.json, src/components/Checkbox/Checkbox.vue, src/components/LobLabel/LobLabel.vue, src/components/RadioButton/RadioButton.vue, src/components/RadioGroup/RadioGroup.vue, src/components/ToggleButton/ToggleButton.vue
[DANG-1429](https://lobsters.atlassian.net/browse/DANG-1429)
sample screenshots:
=> Dang 1429/red/text-error asterisk for all required input fields

CHANGELOG.md, package-lock.json, package.json, src/components/Dropdown/Dropdown.vue
part of [DANG-1455 ](https://lobsters.atlassian.net/browse/DANG-1455) Mapping Dropdown component
- adds isDrawerOpen and hoverOverIndex emits to Dropdown
update: renamed to `open:list`, `close:list`, & `hover:option`
We will use the emitted values to display the CSV Sample values next to the dropdown while the drawer is open and the user is hovering over the list.
=> Dang 1455/add open/close:list & hover:option emits to Dropdown

CHANGELOG.md, package-lock.json, package.json, src/components/Dropzone/Dropzone.mdx, src/components/Dropzone/Dropzone.stories.js, src/components/Dropzone/Dropzone.vue, src/components/Dropzone/__tests__/Dropzone.spec.js
part 1b of [DANG-1448](https://lobsters.atlassian.net/browse/DANG-1448) new Dropzone component
I had started working on the Dropzone before this updated on the Dashboard (so I missed it): 
The fileSizeError has changed from 'File is too large' to '{fileFor} exceeds file size limit of {maxFileSize}'
- add `fileFor` prop
- update computed string for `fileSizeError`
- in Story: update missed `ipnut-id`, rename `file` data to `selectedFile` to avoid warning duplicate from prop
no visual changes other than the file size error message
=> dang-1448/ fix: add fileFor prop to Dropzone, update fileSizeError

CHANGELOG.md, package-lock.json, package.json, src/components/RadioButton/RadioButton.vue
we likely missed this when remodelling the radiobuttons during the live sessions with Tim; we'd updated the other cases but not the `:checked:disabled` one
**before:**
**after:**
=> Fix the size of the Radiobutton dot for when checked and disabled

CHANGELOG.md, package-lock.json, package.json, src/components/MegaButton/MegaButton.vue
[FIGMA](https://www.figma.com/file/S2fDQOmDtOu3wGEYXk9o6x/Campaigns?node-id=3199%3A54642)
* There were some subtle nuances that I missed the first time around.  See image below:  when button is two tone, sometimes the image is flush against the white part and sometimes not. Very tricky trying to get these things to align.  Had to put a set height on the gray part.  Also, the figma shows the megabutton on step 1 being the same width - so in order to achieve that with these new buttons I'm going to have to set a width on the radio buttons, which means I had to add width full to the container in the label, otherwise the gray part was not extending all the way on the x-axis.
=> Dang 1477/more megabutton adjustments

CHANGELOG.md, package-lock.json, package.json, src/components/Modal/Modal.vue
* This relates to [https://lobsters.atlassian.net/browse/DANG-1478](https://lobsters.atlassian.net/browse/DANG-1478)
* There are some subtle changes to the custom envelope selection modal that conflict with some of our current modal defaults.
In the new envelope modal when a selection is made a gray background spans the width of the entire modal.  For this, I needed the option to remove the default padding so I added a new no-padding prop that defaults to false.
The header styling is different in size and position from our defaults, so I just made the header prop not required, this will not break anything in the dashboard and allows me to just add the heading styles as I wish in the EnvelopeModal component (in dashboard).
Here is a screenshot of what the new modal needs to look like:
This …
=> Dang 1478/custom envelope selection in step 3 modal updates

.github/workflows/build-test-lint-publish.yml
[DANG-1559](https://lobsters.atlassian.net/browse/DANG-1559) Migrate ui-components from Netlify to AWS Amplify Hosting
Adding the creation of a git tag and a GitHub Release after publishing to npm
=> Add git tagging and creation of a release upon publish

CHANGELOG.md, package-lock.json, package.json, src/components/MegaButton/MegaButton.vue
...to fix the unwanted scroll-up behavior in step 1 of campaigns
related to [DANG-1572](https://lobsters.atlassian.net/browse/DANG-1572) [Fix unwanted Step 1 scrolling](https://lobsters.atlassian.net/browse/DANG-1572?atlOrigin=eyJpIjoiZTJhY2ViNGJiZDNhNGYxOGE3OGVhYjY0ZjIxNzFlY2EiLCJwIjoiamlyYS1zbGFjay1pbnQifQ)
We have narrowed the 'scroll up behavior' down to the `MegaButton` input having class `absolute` - but without a `relative` parent, an `absolute` element is absolute to the <html> tag / aka top of the page.
<hr>
why the scroll up appeared only the add-on buttons:
- all other `MegaButton`s on Step One are wrapped in a `SectionEditable` that has a `relative` class on it, so the section wrapper is those mega's relative parent
- no wrapper or parent section of the add-ons has any …
=> DANG-1572 / add relative wrapper to MegaButton

CHANGELOG.md, package-lock.json, package.json, src/components/MegaButton/MegaButton.stories.js, src/components/MegaButton/MegaButton.vue
* No ticket, this is part of disabling letter add on buttons in dashboard.
* I need to be able to the full top half of these megabuttons as one image because of the enterprise badges.  Doing this allowed me to get rid of the twoToned and lowerImage props.
=> Update megabuttons for full width top images

CHANGELOG.md, package-lock.json, package.json, src/components/MegaButton/MegaButton.stories.js, src/components/MegaButton/MegaButton.vue
* I accidentally broke the border when a megabutton is selected and has the topFullImage prop with my last PR, this is the fix.
=> Fix megabutton border

CHANGELOG.md, package.json, src/components/Badge/Badge.stories.js, src/components/Badge/Badge.vue
* [https://lobsters.atlassian.net/browse/DANG-1623](https://lobsters.atlassian.net/browse/DANG-1623)
* Adds a gradient variant to the badge component so we can use it as a "beta label"
[Michael and Shampa said this was "good enough"](https://lob.slack.com/archives/C037J0X9PGD/p1664382310081999) in terms of matching the designs without doing too much extra work that may or may not be thrown away soon-ish.
=> DANG-1623/Add gradient variant to badge component (for beta label)

CHANGELOG.md, package-lock.json, package.json, src/components/RadioButtonLarge/RadioButtonLarge.vue, src/components/RadioGroup/RadioGroup.stories.js
To fix [this comment](https://github.com/lob/dashboard-vue/pull/1145#issuecomment-1290636747), I needed `RadioButtonLarge` to be able to go full height. Now, under a group and using this prop, they can look like this:
**BEFORE**
**NOW**
Check the `Large Group With Full Height` story under `Radio Group` in the preview link to check it out.
=> Full height for radio buttons

CHANGELOG.md, package-lock.json, package.json, tailwind.config.js
[DANG-1739 ](https://lobsters.atlassian.net/browse/DANG-1739)
[zeplin link for reference](https://app.zeplin.io/project/6357fb022dba82821ad857bb/screen/6357fb0b4be1e77f26f2e13f)
By adding the new palette to the tailwind plugin and updating the version here, we now have all these fab new colors available. (The old ones will be removed after the rebrand when they are no longer used anywhere)
They are all available to view on the Colors Story
[DEMO LINK HERE](https://pr-355.d11k469e311m4w.amplifyapp.com/?path=/story/theme-dev-only-colors--primary) (scroll down a bit)
_will update changelog & package when ready to go in_
=> dang-1739 / add new color palette to components and display on Theme > Colors story

CHANGELOG.md, package-lock.json, package.json, src/components/Button/Button.vue, src/components/Link/Link.vue
Dang 1739 followup on gray disabled buttons
After the change of the gray color I missed that disabled `Button`s looked faint as well
Per Michael's direction, we are slightly changing the disabled states of our buttons to make them more visible
there are no designs, we did these live on a huddle
before and after screenshots for easy review:
The same changes have been applied to Links that are styled as buttons.
primary disabled
primary warning disabled
secondary disabled 
secondary warning disabled 
subtle disabled
subtle warning disabled
=> Dang 1739 followup on gray disabled buttons

CHANGELOG.md, package-lock.json, package.json, src/components/Breadcrumb/Breadcrumb.vue, src/components/MainNavigation/MainNavigationItem.vue, src/components/MegaMenu/MegaMenuItem.vue
dang-1746 Icons followup
I was advised to also update the MainNav and TopNav Icons on the dashboard in this PR https://github.com/lob/dashboard-vue/pull/1241
This is a temporary fix until we get to update the MainNav and TopNav components to the new designs (we will then figure out how to adjust to our component icons)
- adds `iconClasses` String prop to enable width/height (or any classes) to be added to the Item Icon on the dashboard through the MainNavItem and TopNavItem components
- same for the breadcrumb flag - so it doesn't look out of place
example of Item icon without the classes, and with the `iconClasses` being added to size 20px
=> dang-1746/followup: enable iconClasses for the MainNavItam, MegaMenuItem Icons

CHANGELOG.md, package-lock.json, package.json, src/components/Label/Label.vue, src/components/Label/__tests__/LobLabel.spec.js, src/components/TextInput/TextInput.stories.js, src/components/TextInput/TextInput.vue, src/components/TextInput/__tests__/TextInput.spec.js, src/components/Tooltip/Tooltip.vue
follow up to dang-1754 Update Label style
I realised this is needed while updating the dashboard and a bunch of Label-related tests broke. so this is needed for PR https://github.com/lob/dashboard-vue/pull/1241
- passing `tooltipPosition` through the TextInput to the Label, and making the default `trailing` (for consistency with some of our current forms - this may change in new designs)
- adding z index to the tooltip (it could cut off in some places ie within modal)
- move the tooltip outside the label so the label can be picked up by tests (findByLabelText)
=> dang-1754/fix: LobLabel/TextInput followups

CHANGELOG.md, package-lock.json, package.json, src/components/Icons/AddressBook.vue, src/components/Icons/ChartMixed.vue, src/components/Icons/ChevronDown.vue, src/components/Icons/CodeIcon.vue, src/components/Icons/EnvelopesBulk.vue, src/components/Icons/FileCode.vue, src/components/Icons/Gear.vue, src/components/Icons/HouseChimney.vue, src/components/Icons/LocationDot.vue, src/components/Icons/Webhooks.vue, src/components/MainNavigation/MainNavigation.mdx, src/components/MainNavigation/MainNavigation.stories.js, src/components/MainNavigation/MainNavigation.vue, src/components/MainNavigation/MainNavigationChildItem.vue, src/components/MainNavigation/MainNavigationItem.vue, src/components/MainNavigation/__tests__/MainNavigation.spec.js, src/components/MainNavigation/__tests__/MainNavigationChildItem.spec.js, src/components/MainNavigation/__tests__/MainNavigationItem.spec.js
[DANG-1804](https://lobsters.atlassian.net/browse/DANG-1804) Main Navigation redesign
made to spec of [zeplin](https://app.zeplin.io/project/6357fb022dba82821ad857bb/screen/63939138272909bc462a2bfa) and[ figma](https://www.figma.com/proto/DemxrOr7KWj78cfNVoUw7N/Vision-Design-System?page-id=556%3A4880&node-id=659%3A6728&viewport=472%2C478%2C0.45&scaling=min-zoom) 
This can be seen on the dashboard on this PR https://github.com/lob/dashboard-vue/pull/1257 and [preview link](https://pr-1257.d3ficcvj0bcnwn.amplifyapp.com/).
what changed:
- the Tooltip is now part of the Item component (only shows when !expanded)
- the Icons are now the component Icons put in slots and not img links
- to maintain image accessibility I added `title` to these Icons used here which if paired with `role="img"` on …
=> Dang-1804/ update MainNavigation styles

CHANGELOG.md, package-lock.json, package.json, src/components/Icons/AddressBook.vue, src/components/Icons/ChartMixed.vue, src/components/Icons/ChevronDown.vue, src/components/Icons/CodeIcon.vue, src/components/Icons/EnvelopesBulk.vue, src/components/Icons/FileCode.vue, src/components/Icons/Gear.vue, src/components/Icons/HouseChimney.vue, src/components/Icons/LocationDot.vue, src/components/Icons/Webhooks.vue, src/components/MainNavigation/MainNavigation.mdx, src/components/MainNavigation/MainNavigation.stories.js, src/components/MainNavigation/MainNavigationItem.vue, src/components/MainNavigation/__tests__/MainNavigationItem.spec.js
[DANG-1804](https://lobsters.atlassian.net/browse/DANG-1804) Main Navigation redesign
I run into unexpected side-effects of the icons svgs using titles, a lot of tests broke in the dashboard where Icons are used as part of inputs/buttons - they do not get picked up by `getByLabelText` etc.
So this is removing the titles in icons, and instead uses an aria-label on the MainNavigationItem which is either a link or a button, and both are read by the screen reader when the nav is collapsed.
=> Dang-1804/MainNavigation refresh followup on icons: remove title, use aria-label on the NavItem 

src/components/Dropdown/Dropdown.stories.js
fixes the div width in the Dropdown stories
(not sure how/when this happened)
before/after
=> fix the div width of the Dropdown Story

CHANGELOG.md, package-lock.json, package.json, src/components/Button/Button.vue, src/components/FileUpload/FileUpload.vue, src/components/Link/Link.vue, src/components/TextInput/TextInput.vue
Per Michael's direction, the components should show the black dashed outline only when tabbing and not when clicking. 
These buttons/links are the only components that have it so far - so we just change it from `focus` to `focus-visible`
We keep this in mind for future components and I'll add the same change to the currently open PRs for the inputs.
=> dang-1752/Buttons followup - only show outline for keyboard navigation

.github/CODEOWNERS
* N/A
* Updated the codeowners file to include the @lob/dashboard-and-growth group instead of using our individual GitHub usernames so that when a notification is sent to Slack, we don't get personally notified.
=> Stop tagging me in Slack, GitHub bot (update codeowners to use dashboard group)

CHANGELOG.md, package-lock.json, package.json, src/components/LoadingIndicator/LoadingIndicator.stories.js, src/components/LoadingIndicator/LoadingIndicator.vue
needed for [DANG-1868](https://lobsters.atlassian.net/browse/DANG-1868) Add paper color background to dashboard views
- changes the bg color of LoadingIndicator to transparent
- adds padded and colored bg to the story to demo it
before/after:
[DANG-1868]: https://lobsters.atlassian.net/browse/DANG-1868?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Dang-1868/ loading indicator transparent bg

src/components/MegaButton/MegaButton.vue
[dang-1881](https://lobsters.atlassian.net/browse/DANG-1881) Megabutton touchups for border/outline to match the new system (not a full redesign yet)
- change selected border to black and tabbing outline to black dashed
this is for consistency with the other input elements' black theme
=> dang-1881/Megabutton consistency touchups

CHANGELOG.md, README.md, package.json, src/components/Dropzone/Dropzone.stories.js, src/components/Dropzone/Dropzone.vue, src/mixins/en.js
[GC-109](https://lobsters.atlassian.net/browse/GC-109)
In order to be able to work on [GC-109](https://lobsters.atlassian.net/browse/GC-109) in `dashboard-vue`, I first needed to be able to set `uploading` or `pending` as a status for the dropzone. This way, we can show the creative that was uploaded is still validating.
You can test this by setting the `status` prop in the `Dropzone` story:
[GC-109]: https://lobsters.atlassian.net/browse/GC-109?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[GC-109]: https://lobsters.atlassian.net/browse/GC-109?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> GC-109/add-pending-state-to-dropzone

CHANGELOG.md, package-lock.json, package.json, src/components/RadioGroup/RadioGroup.vue
While doing some related work I noticed a ui bug.
This PR fixes this abomination:
After:
=> GC-246/radio group needs full width

CHANGELOG.md, package-lock.json, package.json, src/components/MegaButton/MegaButton.vue
* [A link to the JIRA ticket](https://lobsters.atlassian.net/browse/GC-431)
* Fixes image overlapping border on megabuttons
=> GC-431/prevent megabutton image from overlapping border

CHANGELOG.md, package.json, src/components/CurrencyInput/CurrencyInput.stories.js, src/components/CurrencyInput/currencyFormatter.js
*Tests were failing server-side on the dashboard due to a lost this context, so this PR explicitly binds the format function to its parent.
[BILL-3100]: https://lobsters.atlassian.net/browse/BILL-3100?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> BILL-3100 Add explicit binding to currency formatter format

CHANGELOG.md, package.json, src/components/TopNavDropdown/TopNavDropdown.vue
* Previous PR was causing console warnings because the new icon variants didn't have titles.
[GC-1373]: https://lobsters.atlassian.net/browse/GC-1373?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> GC-1373 Change TopNavDropdown to not require title prop

CHANGELOG.md, package-lock.json, package.json, src/components/Subnavigation/SubnavigationItem.vue
* There is an issue on the Billing overview page in Dashboard, transaction tab - since the results are paginated, if you flip through them the query string gets pushed onto the url - which then causes the active tab to not think it's active.  By adding this optional stringToMatch prop we can turn it into a regex match so that the pagination query params do not cause the tab to think it's inactive
=> BILL-3514/subnav update

CHANGELOG.md, package.json, src/components/Badge/Badge.stories.js, src/components/Badge/Badge.vue, src/components/Modal/Modal.vue
[GC-1634](https://lobsters.atlassian.net/browse/GC-1634)
In order to achieve [these Figma designs](https://www.figma.com/file/wcnyhGCMthUamrczESUzr3/Event-Based-Campaigns?type=design&node-id=2480-2764&mode=design&t=eP8Bf9iqds8HGC64-0), I needed to make some changes to the modal and badge components:
- Modal: allow removing the section separators/dividers
- Modal: allow a subheading
- Badge: create a new variant for a new gradient
[GC-1634]: https://lobsters.atlassian.net/browse/GC-1634?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> GC-1634/design-updates

CHANGELOG.md, package-lock.json, package.json, src/components/CurrencyInput/CurrencyInput.vue, src/components/CurrencyInput/__tests__/CurrencyInput.spec.js
* [https://lobsters.atlassian.net/browse/GC-2176](https://lobsters.atlassian.net/browse/GC-2176)
* In order to update the Add Lob Credits modal, we need to be able to hide the dollar sign in the `CurrencyInput` component. (Since technically, we're not allowed to say that Lob Credits is money, because that makes Lob a bank, and we don't want to be a bank).
=> GC-2176/Add ability to remove dollar sign from CurrencyInput component

CHANGELOG.md, package-lock.json, package.json, src/components/Table/TableHeader.vue, src/components/Table/TableRow.vue
- [SELF-135](https://lobsters.atlassian.net/browse/SELF-135)
- Fixes the way we are checking for nested slots in tables
- This is the wrong way to do this and will require a stronger fix in the future. This will probably break again in the future when Vue changes the types for nested slots
[SELF-135]: https://lobsters.atlassian.net/browse/SELF-135?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SELF-135: Fix Nested Slots for Tables

CHANGELOG.md, package-lock.json, package.json
- [SELF-135](https://lobsters.atlassian.net/browse/SELF-135)
- A later Vue 3.2 version causes unit tests to fail in `dashboard-vue`
[SELF-135]: https://lobsters.atlassian.net/browse/SELF-135?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SELF-135: Downgrade Vue to 3.2.32

CHANGELOG.md, package-lock.json, package.json, src/components/NumberInput/NumberInput.mdx, src/components/NumberInput/NumberInput.stories.js, src/components/NumberInput/NumberInput.vue, src/components/NumberInput/__tests__/NumberInput.spec.ts
- SELF-168
- Fixes `v-model`
- Adds `containerProps`
**NOTE:** PrimeVue does NOT follow normal Vue conventions for their `InputNumber` component and `v-model`. I am personally not a fan of how they have chosen for this to work
https://github.com/primefaces/primevue/issues/506
- Adds tests to ensure the proper `emits` are happening
=> SELF-168: Fix `NumberInput` `v-model`

CHANGELOG.md, package-lock.json, package.json, src/components/Modal/Modal.stories.js, src/components/Modal/Modal.vue, src/components/Modal/constants.ts, src/types/Color.ts
- [SELF-146](https://lobsters.atlassian.net/browse/SELF-146)
- Adds some more `Modal` `iconColor`s
[SELF-146]: https://lobsters.atlassian.net/browse/SELF-146?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SELF-146: Add `Modal` `iconColor`s

CHANGELOG.md, package-lock.json, package.json, src/components/FloatingActionButton/FloatingActionButton.mdx, src/components/FloatingActionButton/FloatingActionButton.stories.js, src/components/FloatingActionButton/FloatingActionButton.vue, src/components/index.js
[- A link to the JIRA ticket](https://lobsters.atlassian.net/browse/GC-2490)
- The FAB as it exists prior to this PR will center within the viewport. This change will make it center on the parent element
- before
- after
- the element will not appear correctly centered in the Storybook UI. This, unfortunately, seems to be a bug. We might want to revisit the issue if we ever plan on creating horizontal positioning variants.
=> GC-2490 center FAB on parent element

CHANGELOG.md, package-lock.json, package.json, src/components/Modal/Modal.mdx, src/components/Modal/Modal.stories.js, src/components/Modal/Modal.vue
- [SELF-208](https://lobsters.atlassian.net/browse/SELF-208)
- Adds the option to utilize slots with the `Modal` component
[SELF-208]: https://lobsters.atlassian.net/browse/SELF-208?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SELF-208: Add Slots to Modals

package.json, src/components/ColorPicker/BaseColorPicker.vue, src/components/ColorPicker/ColorPicker.d.ts, src/components/ColorPicker/ColorPicker.mdx, src/components/ColorPicker/ColorPicker.stories.ts, src/components/ColorPicker/ColorPicker.vue, src/components/ColorPicker/__tests__/ColorPicker.spec.ts, src/components/ColorPicker/__tests__/__snapshots__/ColorPicker.spec.ts.snap, src/components/ColorPicker/index.ts, src/main.ts, tailwind.config.js
[MI-153](https://lobsters.atlassian.net/browse/MI-153)
Adds a color picker component, which is a clone (rather than a wrapper of) the PrimeVue Color Picker.  The clone has been tweaked to include a hex color input field within the color picker panel, so a specific color value can be entered versus dragging the color and hue handles to arrive at the desired color value.  Additionally, a non-visible hex input field has been added to support accessibility features and be screen reader compatible (not to mention more unit-test friendly).
[MI-153]: https://lobsters.atlassian.net/browse/MI-153?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> MI-153: Add color picker component with hex color input

CHANGELOG.md, package-lock.json, package.json, src/components/ColorPicker/ColorPicker.vue, src/components/ColorPicker/__tests__/ColorPicker.spec.ts
[MI-153](https://lobsters.atlassian.net/browse/MI-153)
Fixes an issue where a hex color code could not be pasted into the ColorPicker's Hex Input
[MI-153]: https://lobsters.atlassian.net/browse/MI-153?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> MI-153: Allow pasting hex color into color picker input

CHANGELOG.md, package-lock.json, package.json, src/components/DateInput/DateInput.stories.js, src/components/DateInput/DateInput.vue
Allows disabling the `<DateInput />` component
=> GC-00/adds disabled prop to DateInput

CHANGELOG.md, package-lock.json, package.json, src/components/IconButton/IconButton.vue
- Icon button didn't pass the mouse event to its click emitter, which prevented the menu/overlay components from working with it.
=> SELF-275/Fix icon button click emitter

CHANGELOG.md, package-lock.json, package.json, src/components/Menu/Menu.vue
- Updates Menu.vue to include menu class with mb-2 if footer slot is present
=> SELF-287 update Menu.vue to include menu class with mb-2 if footer slot is present

.github/actions/install-node-and-npm/action.yml, .github/workflows/codeql.yml, .github/workflows/lint-test.yml, .github/workflows/publish.yml
- [PLAT-2193](https://lobsters.atlassian.net/browse/PLAT-2193)
- `actions/checkout@v3`, `notiz-dev/github-action-json-property@v0.1.0`, `actions/setup-node@v3`, `github/codeql-action/*@v2`,  `JS-DevTools/npm-publish@v1` and `actions/github-script@v5` run Node 12 or 16 and are deprecated, we need them to run Node 20:
See:
https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/
and
https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/
---
_Note: [`notiz-dev/github-action-json-property`](https://github.com/notiz-dev/github-action-json-property) can only be updated to Node 16 as [v0.2.0](https://github.com/notiz-dev/github-action-json-property/releases/tag/v0.2.0) is the latest release (from …
=> update deprecated github actions

CHANGELOG.md, package-lock.json, package.json, src/components/DataTable/DataTable.stories.ts, src/components/DataTable/DataTable.vue, src/components/DataTable/DataTableTotalResults.vue
- Adds an `empty` slot to DataTables for custom empty content
=> SELF-253: Add Empty Slot to DataTable

CHANGELOG.md, package-lock.json, package.json, src/assets/styles/main.scss, src/components/KeyValueInput/KeyValueInput.mdx, src/components/KeyValueInput/KeyValueInput.stories.ts, src/components/KeyValueInput/KeyValueInput.vue, src/components/KeyValueInput/__tests__/KeyValueInput.spec.ts, src/components/KeyValueInput/index.ts, src/main.ts
- [SELF-302](https://lobsters.atlassian.net/browse/SELF-302)
- Dynamic `KeyValueInput` component
[SELF-302]: https://lobsters.atlassian.net/browse/SELF-302?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SELF-302: Add `KeyValueInput` Component

CHANGELOG.md, package-lock.json, package.json, src/components/IconButton/IconButton.vue, src/components/IconButton/constants.ts, src/components/KeyValueInput/KeyValueInput.vue, src/components/Skeleton/Skeleton.mdx, src/components/Skeleton/Skeleton.stories.ts, src/components/Skeleton/Skeleton.vue, src/components/Skeleton/__tests__/Skeleton.spec.ts, src/components/Skeleton/constants.ts, src/components/Skeleton/index.ts, src/main.ts, src/types/Variant.ts
- [SELF-343](https://lobsters.atlassian.net/browse/SELF-343)
- Adds `IconButton` text variant
- Add `Skeleton` component
[SELF-343]: https://lobsters.atlassian.net/browse/SELF-343?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SELF-302: `IconButton` Variant

CHANGELOG.md, package-lock.json, package.json, src/components/Pagination/PaginationTotal.vue, src/components/Tile/Tile.vue, src/main.ts
- [SELF-363](https://lobsters.atlassian.net/browse/SELF-363)
- Skeleton loading
https://github.com/lob/ui-components/assets/77284592/ca8c8a06-48dc-43ee-80be-bb289236e42d
https://github.com/lob/ui-components/assets/77284592/4d3390f2-cb96-4959-8176-e24e4fdf7eb8
https://github.com/lob/ui-components/assets/77284592/c539a204-d556-41f6-abbd-a0fd8c407c82
[SELF-363]: https://lobsters.atlassian.net/browse/SELF-363?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SELF-363: Skeletons

CHANGELOG.md, package-lock.json, package.json, src/components/Modal/Modal.vue
=> SELF-303: Scrollable Modals

CHANGELOG.md, package-lock.json, package.json, src/components/RadioButton/RadioButton.vue, src/components/RadioButton/RadioButtonGroup.vue
- [SELF-438](https://lobsters.atlassian.net/browse/SELF-438)
- Fixes types of attribute props
[SELF-438]: https://lobsters.atlassian.net/browse/SELF-438?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SELF-438: Fix Radio Attribute Typing

CHANGELOG.md, package-lock.json, package.json, src/components/RadioButton/RadioButton.stories.js, src/components/RadioButton/RadioButton.vue, src/components/RadioButton/__tests__/RadioButton.spec.ts
- [A link to the JIRA ticket](https://lobsters.atlassian.net/browse/GC-3207)
- Adds slot `helper` as an alternative to `helperText` to RadioButton. S
=> GC-3207 helper slot for radio button

.storybook/main.js, CHANGELOG.md, package-lock.json, package.json, src/components/FilterContent/FilterContent.stories.js
- [SELF-482](https://lobsters.atlassian.net/browse/SELF-482)
- Resolves a security vulnerability caused by `loader-utils`
- Tested `npm run build`, `npm run storybook`, and installing within another package locally
[SELF-482]: https://lobsters.atlassian.net/browse/SELF-482?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SELF-482: Fix `loader-utils` Vulnerability
